#! /bin/bash -x
# uses gprolog version - make sure to build pl_vsh first

LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH
export LIBRARY_PATH
export PATH=~/bin:$PATH

svg-to-fb <sample.lisp >fb.pro
grash vsh.gsh <fb.pro >self.gsh
