#!/bin/bash -v
# script that runs the components manually w/o grash and leaves intermediate files, for debug purposes
export PATH=/usr/local/bin/:~/bin/:$PATH
BIN=~/bin

$BIN/plscan pl_vsh.graphml >1.txt
sort 1.txt >fb1.pro

gplc pl_check_input.pl --no-top-level 
gplc pl_calc_bounds.pl --no-top-level
gplc pl_mark_directions.pl --no-top-level
gplc pl_match_ports_to_components.pl --no-top-level
gplc pl_assign_pipe_numbers_to_inputs.pl --no-top-level
gplc pl_assign_pipe_numbers_to_outputs.pl --no-top-level
# assign_fds still not working for non-std fd's
gplc pl_assign_fds.pl --no-top-level
gplc pl_emit.pl --no-top-level

mv ./pl_check_input ~/bin
mv ./pl_calc_bounds ~/bin
mv ./pl_mark_directions ~/bin
mv ./pl_match_ports_to_components ~/bin
mv ./pl_assign_pipe_numbers_to_inputs ~/bin
mv ./pl_assign_pipe_numbers_to_outputs ~/bin
mv ./pl_assign_fds ~/bin
mv ./pl_emit ~/bin

pl_check_input <fb1.pro >fb2.pro
pl_calc_bounds <fb2.pro >fb3.pro
pl_mark_directions <fb3.pro >fb4.pro
pl_match_ports_to_components <fb4.pro >fb5.pro
pl_assign_pipe_numbers_to_inputs <fb5.pro >fb6.pro
pl_assign_pipe_numbers_to_outputs <fb6.pro >fb7.pro
pl_assign_fds <fb7.pro >fb8.pro
pl_emit <fb8.pro >fb9.gsh

