#!/bin/bash -x
# use build to create a pipeline in fb9.gsh (using prolog programs to do the build)
# 
# run the resulting grash (.gsh) script, first scanning the graphml then sorting into fb1.pro

export PATH=/usr/local/bin/:~/bin/:$PATH
BIN=~/bin
$BIN/plscan pl_vsh.graphml >1.txt
sort 1.txt >fb1.pro

grash fb9.gsh <fb1.pro >self.gsh

# diff the original against the result to see that they're the same
# diff fb9.gsh self.gsh

