os:
  - linux

dist: xenial

addons:
  apt:
    packages:
      - sbcl
      - haskell-stack

install:
  - echo $(pwd)
  - bash -x ${TRAVIS_BUILD_DIR}/ci/asdf-configure.bash
  - bash -x ${TRAVIS_BUILD_DIR}/ci/quicklisp-install.bash

# Plan  
# 1. Tickle the build mechanism
# 2. Test from Lisp

script:
  - pushd svg && make && popd
  - sbcl --eval '(asdf:load-system :arrowgram)'

