os:
  - linux

dist: xenial

addons:
  apt:
    sources:
      - sbcl
      - haskell-stack

install:
  - echo $(pwd)
  - ./ci/asdf-configure.bash
  - ./ci/quicklisp-install.bash

# Plan  
# 1. Tickle the build mechanism
# 2. Test from Lisp

script:
  - pushd svg && make && popd
  - sbcl --eval '(asdf:load-system :arrowgram)'

