os:
  - linux
  # - osx

dist: bionic
  
language: minimal

addons:
  apt:
    packages:
      - sbcl
      - haskell-stack
  homebrew:
    update: true
    packages:
      - sbcl
      - haskell-stack
      
install:
  - echo $(pwd)
  - bash -x ${TRAVIS_BUILD_DIR}/ci/asdf-configure.bash
  - bash -x ${TRAVIS_BUILD_DIR}/ci/quicklisp-install.bash
  - bash -x ${TRAVIS_BUILD_DIR}/ci/non-quicklisp-dependencies.bash
  - stack install

# Plan  
# 1. Tickle the build mechanism
# 2. Test Quickload from Lisp
# 3. Test Lisp compilation (currently redundant with #2)
script:
  - pushd svg && make && popd
  - sbcl --eval '(ql:quickload :arrowgram)' --eval '(exit :code 0)'
  - sbcl --eval '(asdf:load-system :arrowgram)' --eval '(exit :code 0)'

