all:
	buildapp --output cl-arun \
		--load ~/quicklisp/setup.lisp \
		--load "requires" \
		--load "../cl-build/package" \
		--load "../esa/esa-methods" \
		--load "../esa/esa" \
		--load "make-kind-from-graph" \
		--load "instantiate-kind-recursively" \
		--load "load-and-run" \
		--entry 'arrowgrams/build::main'

