(((:ITEM-KIND . "leaf") (:NAME . "json-array-splitter")
  (:IN-PINS "array" "json") (:OUT-PINS "items" "graph" "error")
  (:KIND . "json-array-splitter")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./json-array-splitter.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "compiler") (:IN-PINS "svg-filename")
  (:OUT-PINS "lisp" "metadata" "json" "error") (:KIND . "compiler")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./compiler.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "part-namer") (:IN-PINS "in")
  (:OUT-PINS "out" "error") (:KIND . "part-namer")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./part-namer.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "children-before-graph")
  (:IN-PINS "graph-name" "graph" "child")
  (:OUT-PINS "name" "graph" "descriptor" "error")
  (:KIND . "children-before-graph")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./children-before-graph.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "schematic-or-leaf")
  (:IN-PINS "manifest-as-json-string")
  (:OUT-PINS "schematic-filename" "child-descriptor" "error")
  (:KIND . "schematic-or-leaf")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./schematic-or-leaf.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "get-manifest-file") (:IN-PINS "in")
  (:OUT-PINS "out" "error") (:KIND . "get-manifest-file")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./get-manifest-file.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "build-collector")
  (:IN-PINS "graph" "name" "descriptor")
  (:OUT-PINS "final-code" "alist" "done" "error") (:KIND . "build-collector")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./build-collector.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "alist-writer") (:IN-PINS "filename" "write")
  (:OUT-PINS "error") (:KIND . "alist-writer")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./alist-writer.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "file-writer") (:IN-PINS "filename" "write")
  (:OUT-PINS "error") (:KIND . "file-writer")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./file-writer.lisp"))
 ((:ITEM-KIND . "graph") (:NAME . "compile-single-diagram")
  (:GRAPH (:NAME . "COMPILE-SINGLE-DIAGRAM") (:INPUTS "SVG-FILENAME")
   (:OUTPUTS "GRAPH" "ERROR" "JSON-FILE-REF" "NAME")
   (:PARTS ((:PART-NAME . "COMPILER") (:KIND-NAME . "COMPILER"))
    ((:PART-NAME . "JSON-ARRAY-SPLITTER") (:KIND-NAME . "JSON-ARRAY-SPLITTER"))
    ((:PART-NAME . "PART-NAMER") (:KIND-NAME . "PART-NAMER")))
   (:WIRING
    ((:WIRE-INDEX . 0) (:SOURCES ((:PART . "PART-NAMER") (:PIN . "OUT")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "NAME"))))
    ((:WIRE-INDEX . 1) (:SOURCES ((:PART . "PART-NAMER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 2)
     (:SOURCES ((:PART . "JSON-ARRAY-SPLITTER") (:PIN . "ITEMS")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "JSON-FILE-REF"))))
    ((:WIRE-INDEX . 3)
     (:SOURCES ((:PART . "JSON-ARRAY-SPLITTER") (:PIN . "GRAPH")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "GRAPH"))))
    ((:WIRE-INDEX . 4)
     (:SOURCES ((:PART . "JSON-ARRAY-SPLITTER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 5) (:SOURCES ((:PART . "COMPILER") (:PIN . "METADATA")))
     (:RECEIVERS ((:PART . "JSON-ARRAY-SPLITTER") (:PIN . "ARRAY"))))
    ((:WIRE-INDEX . 6) (:SOURCES ((:PART . "COMPILER") (:PIN . "JSON")))
     (:RECEIVERS ((:PART . "JSON-ARRAY-SPLITTER") (:PIN . "JSON"))))
    ((:WIRE-INDEX . 7) (:SOURCES ((:PART . "COMPILER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 8) (:SOURCES ((:PART . "SELF") (:PIN . "SVG-FILENAME")))
     (:RECEIVERS ((:PART . "COMPILER") (:PIN . "SVG-FILENAME"))
      ((:PART . "PART-NAMER") (:PIN . "IN")))))))
 ((:ITEM-KIND . "graph") (:NAME . "build-recursive")
  (:GRAPH (:NAME . "BUILD-RECURSIVE") (:INPUTS "SVG-FILENAME")
   (:OUTPUTS "DESCRIPTOR" "ERROR" "GRAPH" "NAME")
   (:PARTS
    ((:PART-NAME . "CHILDREN-BEFORE-GRAPH")
     (:KIND-NAME . "CHILDREN-BEFORE-GRAPH"))
    ((:PART-NAME . "SCHEMATIC-OR-LEAF") (:KIND-NAME . "SCHEMATIC-OR-LEAF"))
    ((:PART-NAME . "GET-MANIFEST-FILE") (:KIND-NAME . "GET-MANIFEST-FILE"))
    ((:PART-NAME . "COMPILE-SINGLE-DIAGRAM")
     (:KIND-NAME . "COMPILE-SINGLE-DIAGRAM")))
   (:WIRING
    ((:WIRE-INDEX . 0)
     (:SOURCES ((:PART . "COMPILE-SINGLE-DIAGRAM") (:PIN . "NAME")))
     (:RECEIVERS ((:PART . "CHILDREN-BEFORE-GRAPH") (:PIN . "GRAPH-NAME"))))
    ((:WIRE-INDEX . 1)
     (:SOURCES ((:PART . "COMPILE-SINGLE-DIAGRAM") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 2)
     (:SOURCES ((:PART . "COMPILE-SINGLE-DIAGRAM") (:PIN . "JSON-FILE-REF")))
     (:RECEIVERS ((:PART . "GET-MANIFEST-FILE") (:PIN . "IN"))))
    ((:WIRE-INDEX . 3)
     (:SOURCES ((:PART . "COMPILE-SINGLE-DIAGRAM") (:PIN . "GRAPH")))
     (:RECEIVERS ((:PART . "CHILDREN-BEFORE-GRAPH") (:PIN . "GRAPH"))))
    ((:WIRE-INDEX . 4)
     (:SOURCES ((:PART . "GET-MANIFEST-FILE") (:PIN . "OUT")))
     (:RECEIVERS
      ((:PART . "SCHEMATIC-OR-LEAF") (:PIN . "MANIFEST-AS-JSON-STRING"))))
    ((:WIRE-INDEX . 5)
     (:SOURCES ((:PART . "GET-MANIFEST-FILE") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 6)
     (:SOURCES ((:PART . "SCHEMATIC-OR-LEAF") (:PIN . "CHILD-DESCRIPTOR")))
     (:RECEIVERS ((:PART . "CHILDREN-BEFORE-GRAPH") (:PIN . "CHILD"))))
    ((:WIRE-INDEX . 7)
     (:SOURCES ((:PART . "SCHEMATIC-OR-LEAF") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 8)
     (:SOURCES ((:PART . "SCHEMATIC-OR-LEAF") (:PIN . "SCHEMATIC-FILENAME")))
     (:RECEIVERS ((:PART . "COMPILE-SINGLE-DIAGRAM") (:PIN . "SVG-FILENAME"))))
    ((:WIRE-INDEX . 9) (:SOURCES ((:PART . "SELF") (:PIN . "SVG-FILENAME")))
     (:RECEIVERS ((:PART . "COMPILE-SINGLE-DIAGRAM") (:PIN . "SVG-FILENAME"))))
    ((:WIRE-INDEX . 10)
     (:SOURCES ((:PART . "CHILDREN-BEFORE-GRAPH") (:PIN . "NAME")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "NAME"))))
    ((:WIRE-INDEX . 11)
     (:SOURCES ((:PART . "CHILDREN-BEFORE-GRAPH") (:PIN . "GRAPH")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "GRAPH"))))
    ((:WIRE-INDEX . 12)
     (:SOURCES ((:PART . "CHILDREN-BEFORE-GRAPH") (:PIN . "DESCRIPTOR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "DESCRIPTOR"))))
    ((:WIRE-INDEX . 13)
     (:SOURCES ((:PART . "CHILDREN-BEFORE-GRAPH") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR")))))))
 ((:ITEM-KIND . "graph") (:NAME . "build")
  (:GRAPH (:NAME . "BUILD") (:INPUTS "SVG-FILENAME" "DONE")
   (:OUTPUTS "JSON-COLLECTION" "ALIST" "DONE" "ERROR")
   (:PARTS ((:PART-NAME . "BUILD-COLLECTOR") (:KIND-NAME . "BUILD-COLLECTOR"))
    ((:PART-NAME . "BUILD-RECURSIVE") (:KIND-NAME . "BUILD-RECURSIVE")))
   (:WIRING
    ((:WIRE-INDEX . 0) (:SOURCES ((:PART . "SELF") (:PIN . "SVG-FILENAME")))
     (:RECEIVERS ((:PART . "BUILD-RECURSIVE") (:PIN . "SVG-FILENAME"))))
    ((:WIRE-INDEX . 1) (:SOURCES ((:PART . "SELF") (:PIN . "DONE")))
     (:RECEIVERS ((:PART . "BUILD-RECURSIVE") (:PIN . "DONE"))))
    ((:WIRE-INDEX . 2)
     (:SOURCES ((:PART . "BUILD-RECURSIVE") (:PIN . "GRAPH")))
     (:RECEIVERS ((:PART . "BUILD-COLLECTOR") (:PIN . "GRAPH"))))
    ((:WIRE-INDEX . 3) (:SOURCES ((:PART . "BUILD-RECURSIVE") (:PIN . "NAME")))
     (:RECEIVERS ((:PART . "BUILD-COLLECTOR") (:PIN . "NAME"))))
    ((:WIRE-INDEX . 4)
     (:SOURCES ((:PART . "BUILD-RECURSIVE") (:PIN . "DESCRIPTOR")))
     (:RECEIVERS ((:PART . "BUILD-COLLECTOR") (:PIN . "DESCRIPTOR"))))
    ((:WIRE-INDEX . 5)
     (:SOURCES ((:PART . "BUILD-RECURSIVE") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 6) (:SOURCES ((:PART . "BUILD-COLLECTOR") (:PIN . "DONE")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "DONE"))))
    ((:WIRE-INDEX . 7)
     (:SOURCES ((:PART . "BUILD-COLLECTOR") (:PIN . "FINAL-CODE")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "JSON-COLLECTION"))))
    ((:WIRE-INDEX . 8)
     (:SOURCES ((:PART . "BUILD-COLLECTOR") (:PIN . "ALIST")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ALIST"))))
    ((:WIRE-INDEX . 9)
     (:SOURCES ((:PART . "BUILD-COLLECTOR") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR")))))))
 ((:ITEM-KIND . "graph") (:NAME . "build-json")
  (:GRAPH (:NAME . "BUILD-JSON")
   (:INPUTS "ALIST-FILENAME" "OUTPUT-FILENAME" "SVG-FILENAME" "DONE")
   (:OUTPUTS "ERROR")
   (:PARTS ((:PART-NAME . "BUILD") (:KIND-NAME . "BUILD"))
    ((:PART-NAME . "ALIST-WRITER") (:KIND-NAME . "ALIST-WRITER"))
    ((:PART-NAME . "FILE-WRITER") (:KIND-NAME . "FILE-WRITER")))
   (:WIRING
    ((:WIRE-INDEX . 0) (:SOURCES ((:PART . "SELF") (:PIN . "ALIST-FILENAME")))
     (:RECEIVERS ((:PART . "ALIST-WRITER") (:PIN . "FILENAME"))))
    ((:WIRE-INDEX . 1) (:SOURCES ((:PART . "SELF") (:PIN . "OUTPUT-FILENAME")))
     (:RECEIVERS ((:PART . "FILE-WRITER") (:PIN . "FILENAME"))))
    ((:WIRE-INDEX . 2) (:SOURCES ((:PART . "SELF") (:PIN . "SVG-FILENAME")))
     (:RECEIVERS ((:PART . "BUILD") (:PIN . "SVG-FILENAME"))))
    ((:WIRE-INDEX . 3) (:SOURCES ((:PART . "SELF") (:PIN . "DONE")))
     (:RECEIVERS ((:PART . "BUILD") (:PIN . "DONE"))))
    ((:WIRE-INDEX . 4) (:SOURCES ((:PART . "FILE-WRITER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 5) (:SOURCES ((:PART . "ALIST-WRITER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 6) (:SOURCES ((:PART . "BUILD") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 7)
     (:SOURCES ((:PART . "BUILD") (:PIN . "JSON-COLLECTION")))
     (:RECEIVERS ((:PART . "FILE-WRITER") (:PIN . "WRITE"))))
    ((:WIRE-INDEX . 8) (:SOURCES ((:PART . "BUILD") (:PIN . "ALIST")))
     (:RECEIVERS ((:PART . "ALIST-WRITER") (:PIN . "WRITE"))))))))