(in-package :arrowgrams/parser)

#+nil(defconstant +builtins+ '(:LISPV/2 :LISP/1 CL::<=/2 CL::>=/2 :!/0 :WRITE/2 :NL/1
                          :inc/2 :dec/2 :g_read/2 :g_assign/2
                          PROLOG::pl-fail/0 PROLOG::PL-TRUE/0 prolog::not-same/2))

(defconstant +builtins+ nil)

(defconstant +facts+ '(
                    :ARROW/1
                    :ARROW_X/2
                    :ARROW_Y/2
                    :BOUNDING_BOX_BOTTOM/2
                    :BOUNDING_BOX_LEFT/2
                    :BOUNDING_BOX_RIGHT/2
                    :BOUNDING_BOX_TOP/2
                    :CENTER_X/2
                    :CENTER_Y/2
                    :COMPONENT/1
                    :EDGE/1
                    :ELTYPE/2
                    :GEOMETRY_H/2
                    :GEOMETRY_W/2
                    :GEOMETRY_LEFT_X/2
                    :GEOMETRY_CENTER_X/2
                    :GEOMETRY_CENTER_Y/2
                    :GEOMETRY_TOP_Y/2
                    :KIND/2
                    :SELFPORT/2
                    :LINE/1
                    :LINE_BEGIN_X/2
                    :LINE_BEGIN_Y/2
                    :LINE_END_X/2
                    :LINE_END_Y/2
                    :MOVE_ABSOLUTE_X/2
                    :MOVE_ABSOLUTE_Y/2
                    :MOVE_RELATIVE_X/2
                    :MOVE_RELATIVE_Y/2
                    :NPIPES/1
                    :NWIRES/1
                    :PARENT/2
                    :PIPENUM/2
                    :WIRENUM/2
                    :PORT/1
                    :PORTNAME/2
                    :PORTNAMEBYID/2
                    :UNASSIGNED/1
                    :SOURCE/2
                    :SOURCE_X/2
                    :SOURCE_Y/2
                    :SINK_X/2
                    :SINK_Y/2
                    :RECT/1
                    :ROUNDEDRECT/1
                    :PINLESS/1
                    :SPEECHBUBBLE/1
                    :COMMENT/1
                    :METADATA/2
                    :ELLIPSE/1
                    :DOT/1
                    :SINK/2
                    :SINKFD/2
                    :SOURCE/2
                    :SOURCEFD/2
                    :STROKE_ABSOLUTE_X/2
                    :STROKE_ABSOLUTE_Y/2
                    :STROKE_RELATIVE_X/2
                    :STROKE_RELATIVE_Y/2
                    :USED/1
                    :TEXT/2
                    :TEXT_X/2
                    :TEXT_Y/2
                    :TEXT_W/2
                    :TEXT_H/2
                    :JOIN_CENTERPAIR/2
                    :JOIN_DISTANCE/2
                    :DISTANCE_XY/2
                    :INPUTPIN/2
                    :OUTPUTPIN/2
                    :SELFINPUTPIN/2
                    :SELFOUTPUTPIN/2
                    :SELFINPUTPIN/1
                    :SELFOUTPUTPIN/1
                    :INPUTPIN/2
                    :OUTPUTPIN/2
                    :INPUTPORT/2
                    :OUTPUTPORT/2
                    :WIREINDEX/2
                    :N_C/1
                    :NAMEDSINK/1
                    :NAMEDSOURCE/1
                    :LOG/1
                    :LOG/2
                    :LOG/3
                    :LOG/4
                    :LOG/5
                    :LOG/6
                    :LOG/7
                    :LOG/8
                    :LOG/9
                    ))
