(ql:quickload :esrap)
(load "/Users/tarvydas/quicklisp/local-projects/bmfbp/svg/prolog2lisp3/package.lisp")
(load "/Users/tarvydas/quicklisp/local-projects/bmfbp/svg/prolog2lisp3/low-level.lisp")
(load "/Users/tarvydas/quicklisp/local-projects/bmfbp/svg/prolog2lisp3/prolog-peg.lisp")
(load "/Users/tarvydas/quicklisp/local-projects/bmfbp/svg/prolog2lisp3/explore.lisp")
(in-package :arrowgrams/parser)
