name:                svg-to-fb
version:             0.1.0.0
github:              "githubuser/svg-to-fb"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/svg-to-fb#readme>

dependencies:
- base
- directory
- text
- taggy
- regex-posix
- unordered-containers
- svg-tree == 0.6.2.3
- attoparsec
- linear

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

executables:
  svg-to-fb:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - svg-to-fb

tests:
  svg-to-fb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - svg-to-fb
