(((:ITEM-KIND . "leaf") (:NAME . "build-collector")
  (:IN-PINS "graph" "name" "descriptor")
  (:OUT-PINS "final-code" "alist" "done" "error") (:KIND . "build-collector")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./build-collector.lisp"))
 ((:ITEM-KIND . "graph") (:NAME . "build")
  (:GRAPH (:NAME . "BUILD") (:INPUTS "SVG-FILENAME" "DONE")
   (:OUTPUTS "JSON-COLLECTION" "ALIST" "DONE" "ERROR")
   (:PARTS ((:PART-NAME . "BUILD-COLLECTOR") (:KIND-NAME . "BUILD-COLLECTOR"))
    ((:PART-NAME . "BUILD-RECURSIVE") (:KIND-NAME . "BUILD-RECURSIVE")))
   (:WIRING
    ((:WIRE-INDEX . 0) (:SOURCES ((:PART . "SELF") (:PIN . "SVG-FILENAME")))
     (:RECEIVERS ((:PART . "BUILD-RECURSIVE") (:PIN . "SVG-FILENAME"))))
    ((:WIRE-INDEX . 1) (:SOURCES ((:PART . "SELF") (:PIN . "DONE")))
     (:RECEIVERS ((:PART . "BUILD-RECURSIVE") (:PIN . "DONE"))))
    ((:WIRE-INDEX . 2)
     (:SOURCES ((:PART . "BUILD-RECURSIVE") (:PIN . "GRAPH")))
     (:RECEIVERS ((:PART . "BUILD-COLLECTOR") (:PIN . "GRAPH"))))
    ((:WIRE-INDEX . 3) (:SOURCES ((:PART . "BUILD-RECURSIVE") (:PIN . "NAME")))
     (:RECEIVERS ((:PART . "BUILD-COLLECTOR") (:PIN . "NAME"))))
    ((:WIRE-INDEX . 4)
     (:SOURCES ((:PART . "BUILD-RECURSIVE") (:PIN . "DESCRIPTOR")))
     (:RECEIVERS ((:PART . "BUILD-COLLECTOR") (:PIN . "DESCRIPTOR"))))
    ((:WIRE-INDEX . 5)
     (:SOURCES ((:PART . "BUILD-RECURSIVE") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 6) (:SOURCES ((:PART . "BUILD-COLLECTOR") (:PIN . "DONE")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "DONE"))))
    ((:WIRE-INDEX . 7)
     (:SOURCES ((:PART . "BUILD-COLLECTOR") (:PIN . "FINAL-CODE")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "JSON-COLLECTION"))))
    ((:WIRE-INDEX . 8)
     (:SOURCES ((:PART . "BUILD-COLLECTOR") (:PIN . "ALIST")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ALIST"))))
    ((:WIRE-INDEX . 9)
     (:SOURCES ((:PART . "BUILD-COLLECTOR") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))))))