(((:ITEM-KIND . "leaf") (:NAME . "alist-writer") (:IN-PINS "filename" "write")
  (:OUT-PINS "error") (:KIND . "alist-writer")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./alist-writer.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "file-writer") (:IN-PINS "filename" "write")
  (:OUT-PINS "error") (:KIND . "file-writer")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./file-writer.lisp"))
 ((:ITEM-KIND . "graph") (:NAME . "build-json")
  (:GRAPH (:NAME . "BUILD-JSON")
   (:INPUTS "ALIST-FILENAME" "OUTPUT-FILENAME" "SVG-FILENAME" "DONE")
   (:OUTPUTS "ERROR")
   (:PARTS ((:PART-NAME . "BUILD") (:KIND-NAME . "BUILD"))
    ((:PART-NAME . "ALIST-WRITER") (:KIND-NAME . "ALIST-WRITER"))
    ((:PART-NAME . "FILE-WRITER") (:KIND-NAME . "FILE-WRITER")))
   (:WIRING
    ((:WIRE-INDEX . 0) (:SOURCES ((:PART . "SELF") (:PIN . "ALIST-FILENAME")))
     (:RECEIVERS ((:PART . "ALIST-WRITER") (:PIN . "FILENAME"))))
    ((:WIRE-INDEX . 1) (:SOURCES ((:PART . "SELF") (:PIN . "OUTPUT-FILENAME")))
     (:RECEIVERS ((:PART . "FILE-WRITER") (:PIN . "FILENAME"))))
    ((:WIRE-INDEX . 2) (:SOURCES ((:PART . "SELF") (:PIN . "SVG-FILENAME")))
     (:RECEIVERS ((:PART . "BUILD") (:PIN . "SVG-FILENAME"))))
    ((:WIRE-INDEX . 3) (:SOURCES ((:PART . "SELF") (:PIN . "DONE")))
     (:RECEIVERS ((:PART . "BUILD") (:PIN . "DONE"))))
    ((:WIRE-INDEX . 4) (:SOURCES ((:PART . "FILE-WRITER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 5) (:SOURCES ((:PART . "ALIST-WRITER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 6) (:SOURCES ((:PART . "BUILD") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 7)
     (:SOURCES ((:PART . "BUILD") (:PIN . "JSON-COLLECTION")))
     (:RECEIVERS ((:PART . "FILE-WRITER") (:PIN . "WRITE"))))
    ((:WIRE-INDEX . 8) (:SOURCES ((:PART . "BUILD") (:PIN . "ALIST")))
     (:RECEIVERS ((:PART . "ALIST-WRITER") (:PIN . "WRITE"))))))))