(((:ITEM-KIND . "leaf") (:NAME . "json-array-splitter")
  (:IN-PINS "array" "json") (:OUT-PINS "items" "graph" "error")
  (:KIND . "json-array-splitter")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./json-array-splitter.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "compiler") (:IN-PINS "svg-filename")
  (:OUT-PINS "lisp" "metadata" "json" "error") (:KIND . "compiler")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./compiler.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "part-namer") (:IN-PINS "in")
  (:OUT-PINS "out" "error") (:KIND . "part-namer")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./part-namer.lisp"))
 ((:ITEM-KIND . "graph") (:NAME . "compile-single-diagram")
  (:GRAPH (:NAME . "COMPILE-SINGLE-DIAGRAM") (:INPUTS "SVG-FILENAME")
   (:OUTPUTS "GRAPH" "ERROR" "JSON-FILE-REF" "NAME")
   (:PARTS ((:PART-NAME . "COMPILER") (:KIND-NAME . "COMPILER"))
    ((:PART-NAME . "JSON-ARRAY-SPLITTER") (:KIND-NAME . "JSON-ARRAY-SPLITTER"))
    ((:PART-NAME . "PART-NAMER") (:KIND-NAME . "PART-NAMER")))
   (:WIRING
    ((:WIRE-INDEX . 0) (:SOURCES ((:PART . "PART-NAMER") (:PIN . "OUT")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "NAME"))))
    ((:WIRE-INDEX . 1) (:SOURCES ((:PART . "PART-NAMER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 2)
     (:SOURCES ((:PART . "JSON-ARRAY-SPLITTER") (:PIN . "ITEMS")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "JSON-FILE-REF"))))
    ((:WIRE-INDEX . 3)
     (:SOURCES ((:PART . "JSON-ARRAY-SPLITTER") (:PIN . "GRAPH")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "GRAPH"))))
    ((:WIRE-INDEX . 4)
     (:SOURCES ((:PART . "JSON-ARRAY-SPLITTER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 5) (:SOURCES ((:PART . "COMPILER") (:PIN . "METADATA")))
     (:RECEIVERS ((:PART . "JSON-ARRAY-SPLITTER") (:PIN . "ARRAY"))))
    ((:WIRE-INDEX . 6) (:SOURCES ((:PART . "COMPILER") (:PIN . "JSON")))
     (:RECEIVERS ((:PART . "JSON-ARRAY-SPLITTER") (:PIN . "JSON"))))
    ((:WIRE-INDEX . 7) (:SOURCES ((:PART . "COMPILER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 8) (:SOURCES ((:PART . "SELF") (:PIN . "SVG-FILENAME")))
     (:RECEIVERS ((:PART . "COMPILER") (:PIN . "SVG-FILENAME"))
      ((:PART . "PART-NAMER") (:PIN . "IN"))))))))