name:                svg-to-fb
version:             0.1.0.0
github:              "githubuser/svg-to-fb"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/svg-to-fb#readme>

dependencies:
- base >= 4.7 && < 5
- directory == 1.3.1.5
- text == 1.2.3.1
- taggy == 0.2.1
- regex-posix == 0.95.2
- unordered-containers == 0.2.9.0
- svg-tree == 0.6.2.3
- attoparsec == 0.13.2.2
- linear == 1.20.8

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

executables:
  svg-to-fb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - svg-to-fb

tests:
  svg-to-fb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - svg-to-fb
