#!/bin/sh

CLASS=`basename $1 .lisp`

cp $1 old/$1

sed -e "3i\\
(defclass ${CLASS} (e/part:part) ())" <$1 | \

sed -e "4i\\
(defmethod e/part:busy-p ((self ${CLASS})) (call-next-method))"  | \

sed -e "s~self e/part:part~self ${CLASS}~" | \

sed -e "s~[-a-zA-Z]*-first-time~e/part:first-time~" | \

sed -e "s~[-a-zA-Z]*-react~e/part:react~"  | \

sed -e 's/cl-event-passing-user::@send/@send/g' | \
sed -e 's/cl-event-passing-user::@set-instance-var/@set/g' |  \
sed -e 's/cl-event-passing-user::@get-instance-var/@get/g' >$1.oo
