(HELLOWORLD-HELLOWORLD-BOOTSTRAP (START)
   (RESULT)
  
  (:code STRING-JOIN (B A) (C))
  (:code WORLD (START) (S))
  (:code HELLO (START) (S))
  "
    HELLO.S -> STRING-JOIN.A
    WORLD.S -> STRING-JOIN.B
    STRING-JOIN.C -> SELF.RESULT
    SELF.START -> WORLD.START,HELLO.START
    ")