(struidG0 "out")
(struidG2 "out")
(struidG4 "out")
(struidG5 "in")
(struidG7 "in")
(struidG8 "metadata json")
(struidG9 "split metadata")
(struidG10 "composite json")
(struidG11 "compile one arrowgram")
(struidG12 "arrowgram")
(struidG13 "[{\"gitRef\":\"master\",\"kindName\":\"compile one arrowgram\",\"manifestPath\":\"compile_one_arrowgram.manifest.json\",\"contextDir\":\"build_process/parts/\",\"gitUrl\":\"https://github.com/bmfbp/bmfbp.git\"},{\"gitRef\":\"master\",\"kindName\":\"split metadata\",\"manifestPath\":\"split_metadata.manifest.json\",\"contextDir\":\"build_process/parts/\",\"gitUrl\":\"https://github.com/bmfbp/bmfbp.git\"}]")
