#!/bin/sh
./cvtoo add-kinds.lisp
./cvtoo add-self-ports.lisp
./cvtoo assign-parents-to-ellipses.lisp
./cvtoo assign-portnames.lisp
./cvtoo assign-wire-numbers-to-edges.lisp
./cvtoo bounding-boxes.lisp
./cvtoo calculate-distances.lisp
./cvtoo classes.lisp
./cvtoo closest.lisp
./cvtoo coincident-ports.lisp
./cvtoo compiler.lisp
./cvtoo create-centers.lisp
./cvtoo demux.lisp
./cvtoo ellipse-bounding-boxes.lisp
./cvtoo fb.lisp
./cvtoo find-comments.lisp
./cvtoo find-metadata.lisp
./cvtoo input-pins.lisp
./cvtoo ir-emitter.lisp
./cvtoo junk.lisp
./cvtoo make-unknown-port-names.lisp
./cvtoo mark-directions.lisp
./cvtoo mark-indexed-ports.lisp
./cvtoo mark-nc.lisp
./cvtoo match-ports-to-components.lisp
./cvtoo meta-proto.lisp
./cvtoo old-assign-portnames.lisp
./cvtoo output-pins.lisp
./cvtoo package.lisp
./cvtoo pass.lisp
./cvtoo pinless.lisp
./cvtoo rectangle-bounding-boxes.lisp
./cvtoo rules-util.lisp
./cvtoo rules.lisp
./cvtoo self-input-pins.lisp
./cvtoo self-output-pins.lisp
./cvtoo sem-no-duplicate-kinds.lisp
./cvtoo sem-parts-have-some-ports.lisp
./cvtoo sem-ports-have-sink-or-source.lisp
./cvtoo sem-speech-vs-comments.lisp
./cvtoo sequencer.lisp
./cvtoo speechbubble-bounding-boxes.lisp
./cvtoo text-bounding-boxes.lisp
./cvtoo util.lisp
./cvtoo writer.lisp
