; parts
(ellipse-bb rectangle-bb text-bb speechbubble-bb 
assign-parents-to-ellipses find-comments find-metadata add-kinds add-self-ports
make-unknown-port-names create-centers calculate-distances assign-portnames mark-indexed-ports concident-ports mark-directions
match-ports-to-components pinless sem-parts-have-some-ports sem-ports-have-sink-or-source sem-no-duplicate-kinds
sem-speech-vs-comments assign-wire-numbers-to-edges self-input-pins self-output-pins input-pins output-pins)

; wires
(

(((:SELF :FB)) ((ELLIPSE-BB :FB) (RECTANGLE-BB :FB) (TEXT-BB :FB) (SPEECHBUBBLE-BB :FB) (ASSIGN-PARENTS-TO-ELLIPSES :FB) (FIND-COMMENTS :FB) (FIND-METADATA :FB) (ADD-KINDS :FB) (ADD-SELF-PORTS :FB) (MAKE-UNKNOWN-PORT-NAMES :FB) (CREATE-CENTERS :FB) (CALCULATE-DISTANCES :FB) (ASSIGN-PORTNAMES :FB) (MARK-INDEXED-PORTS :FB) (CONCIDENT-PORTS :FB) (MARK-DIRECTIONS :FB) (MATCH-PORTS-TO-COMPONENTS :FB) (PINLESS :FB) (SEM-PARTS-HAVE-SOME-PORTS :FB) (SEM-PORTS-HAVE-SINK-OR-SOURCE :FB) (SEM-NO-DUPLICATE-KINDS :FB) (SEM-SPEECH-VS-COMMENTS :FB) (ASSIGN-WIRE-NUMBERS-TO-EDGES :FB) (SELF-INPUT-PINS :FB) (SELF-OUTPUT-PINS :FB) (INPUT-PINS :FB) (OUTPUT-PINS :FB)))

(((ELLIPSE-BB :REQUEST-FB) (RECTANGLE-BB :REQUEST-FB) (TEXT-BB :REQUEST-FB) (SPEECHBUBBLE-BB :REQUEST-FB) (ASSIGN-PARENTS-TO-ELLIPSES :REQUEST-FB) (FIND-COMMENTS :REQUEST-FB) (FIND-METADATA :REQUEST-FB) (ADD-KINDS :REQUEST-FB) (ADD-SELF-PORTS :REQUEST-FB) (MAKE-UNKNOWN-PORT-NAMES :REQUEST-FB) (CREATE-CENTERS :REQUEST-FB) (CALCULATE-DISTANCES :REQUEST-FB) (ASSIGN-PORTNAMES :REQUEST-FB) (MARK-INDEXED-PORTS :REQUEST-FB) (CONCIDENT-PORTS :REQUEST-FB) (MARK-DIRECTIONS :REQUEST-FB) (MATCH-PORTS-TO-COMPONENTS :REQUEST-FB) (PINLESS :REQUEST-FB) (SEM-PARTS-HAVE-SOME-PORTS :REQUEST-FB) (SEM-PORTS-HAVE-SINK-OR-SOURCE :REQUEST-FB) (SEM-NO-DUPLICATE-KINDS :REQUEST-FB) (SEM-SPEECH-VS-COMMENTS :REQUEST-FB) (ASSIGN-WIRE-NUMBERS-TO-EDGES :REQUEST-FB) (SELF-INPUT-PINS :REQUEST-FB) (SELF-OUTPUT-PINS :REQUEST-FB) (INPUT-PINS :REQUEST-FB) (OUTPUT-PINS :REQUEST-FB)) ((:SELF :REQUEST-FB)))

(((ELLIPSE-BB :ADD-FACT) (RECTANGLE-BB :ADD-FACT) (TEXT-BB :ADD-FACT) (SPEECHBUBBLE-BB :ADD-FACT) (ASSIGN-PARENTS-TO-ELLIPSES :ADD-FACT) (FIND-COMMENTS :ADD-FACT) (FIND-METADATA :ADD-FACT) (ADD-KINDS :ADD-FACT) (ADD-SELF-PORTS :ADD-FACT) (MAKE-UNKNOWN-PORT-NAMES :ADD-FACT) (CREATE-CENTERS :ADD-FACT) (CALCULATE-DISTANCES :ADD-FACT) (ASSIGN-PORTNAMES :ADD-FACT) (MARK-INDEXED-PORTS :ADD-FACT) (CONCIDENT-PORTS :ADD-FACT) (MARK-DIRECTIONS :ADD-FACT) (MATCH-PORTS-TO-COMPONENTS :ADD-FACT) (PINLESS :ADD-FACT) (SEM-PARTS-HAVE-SOME-PORTS :ADD-FACT) (SEM-PORTS-HAVE-SINK-OR-SOURCE :ADD-FACT) (SEM-NO-DUPLICATE-KINDS :ADD-FACT) (SEM-SPEECH-VS-COMMENTS :ADD-FACT) (ASSIGN-WIRE-NUMBERS-TO-EDGES :ADD-FACT) (SELF-INPUT-PINS :ADD-FACT) (SELF-OUTPUT-PINS :ADD-FACT) (INPUT-PINS :ADD-FACT) (OUTPUT-PINS :ADD-FACT)) ((:SELF :ADD-FACT)))

(((ELLIPSE-BB :DONE) (RECTANGLE-BB :GO))
 ((RECTANGLE-BB :DONE) (TEXT-BB :GO))
 ((TEXT-BB :DONE) (SPEECHBUBBLE-BB :GO))
 ((SPEECHBUBBLE-BB :DONE) (ASSIGN-PARENTS-TO-ELLIPSES :GO))
 ((ASSIGN-PARENTS-TO-ELLIPSES :DONE) (FIND-COMMENTS :GO))
 ((FIND-COMMENTS :DONE) (FIND-METADATA :GO))
 ((FIND-METADATA :DONE) (ADD-KINDS :GO))
 ((ADD-KINDS :DONE) (ADD-SELF-PORTS :GO))
 ((ADD-SELF-PORTS :DONE) (MAKE-UNKNOWN-PORT-NAMES :GO))
 ((MAKE-UNKNOWN-PORT-NAMES :DONE) (CREATE-CENTERS :GO))
 ((CREATE-CENTERS :DONE) (CALCULATE-DISTANCES :GO))
 ((CALCULATE-DISTANCES :DONE) (ASSIGN-PORTNAMES :GO))
 ((ASSIGN-PORTNAMES :DONE) (MARK-INDEXED-PORTS :GO))
 ((MARK-INDEXED-PORTS :DONE) (CONCIDENT-PORTS :GO))
 ((CONCIDENT-PORTS :DONE) (MARK-DIRECTIONS :GO))
 ((MARK-DIRECTIONS :DONE) (MATCH-PORTS-TO-COMPONENTS :GO))
 ((MATCH-PORTS-TO-COMPONENTS :DONE) (PINLESS :GO))
 ((PINLESS :DONE) (SEM-PARTS-HAVE-SOME-PORTS :GO))
 ((SEM-PARTS-HAVE-SOME-PORTS :DONE) (SEM-PORTS-HAVE-SINK-OR-SOURCE :GO))
 ((SEM-PORTS-HAVE-SINK-OR-SOURCE :DONE) (SEM-NO-DUPLICATE-KINDS :GO))
 ((SEM-NO-DUPLICATE-KINDS :DONE) (SEM-SPEECH-VS-COMMENTS :GO))
 ((SEM-SPEECH-VS-COMMENTS :DONE) (ASSIGN-WIRE-NUMBERS-TO-EDGES :GO))
 ((ASSIGN-WIRE-NUMBERS-TO-EDGES :DONE) (SELF-INPUT-PINS :GO))
 ((SELF-INPUT-PINS :DONE) (SELF-OUTPUT-PINS :GO))
 ((SELF-OUTPUT-PINS :DONE) (INPUT-PINS :GO))
 ((INPUT-PINS :DONE) (OUTPUT-PINS :GO)))

(((ELLIPSE-BB :ERROR) (RECTANGLE-BB :ERROR) (TEXT-BB :ERROR) (SPEECHBUBBLE-BB :ERROR) (ASSIGN-PARENTS-TO-ELLIPSES :ERROR) (FIND-COMMENTS :ERROR) (FIND-METADATA :ERROR) (ADD-KINDS :ERROR) (ADD-SELF-PORTS :ERROR) (MAKE-UNKNOWN-PORT-NAMES :ERROR) (CREATE-CENTERS :ERROR) (CALCULATE-DISTANCES :ERROR) (ASSIGN-PORTNAMES :ERROR) (MARK-INDEXED-PORTS :ERROR) (CONCIDENT-PORTS :ERROR) (MARK-DIRECTIONS :ERROR) (MATCH-PORTS-TO-COMPONENTS :ERROR) (PINLESS :ERROR) (SEM-PARTS-HAVE-SOME-PORTS :ERROR) (SEM-PORTS-HAVE-SINK-OR-SOURCE :ERROR) (SEM-NO-DUPLICATE-KINDS :ERROR) (SEM-SPEECH-VS-COMMENTS :ERROR) (ASSIGN-WIRE-NUMBERS-TO-EDGES :ERROR) (SELF-INPUT-PINS :ERROR) (SELF-OUTPUT-PINS :ERROR) (INPUT-PINS :ERROR) (OUTPUT-PINS :ERROR)) ((:SELF :ERROR)))

)
