name:                hs-parts
version:             0.1.0.0

dependencies:
- base
- text
- attoparsec

library:
  default-extensions:
    - OverloadedStrings
  source-dirs: src

executables:
  http-receive:
    main:                HttpReceiveApp.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is HttpReceiveApp
    dependencies:
    - hs-parts

  http-send:
    main:                HttpSendApp.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is HttpSendApp
    dependencies:
    - hs-parts
