(in-package :diagram)

(defun reset ()
  (let ((keys nil)
        (peg-package (find-package :peg))
        (peg-grammar-package (find-package :peg-grammar)))
    (maphash #'(lambda (k v)
                 (declare (ignore v))
                 (let ((pkg (symbol-package k)))
                   (unless (or (equal peg-package pkg) (equal peg-grammar-package pkg))
                     (push k keys))))
             esrap::*rules*)
    (mapc #'(lambda (k)
              (remhash k esrap::*rules*))
          keys)))

(defun again ()
  (reset)
  (ql:quickload :diagram)
  (test))