(in-package :paip)

(PAIP::<- (CREATERECTBOUNDINGBOX ?ID)
          (GEOMETRY_LEFT_X ?ID ?X)
          (GEOMETRY_TOP_Y ?ID ?Y)
          (GEOMETRY_W ?ID ?WIDTH)
          (GEOMETRY_H ?ID ?HEIGHT)
          (asserta (BOUNDING_BOX_LEFT ?ID ?X))
          (asserta (BOUNDING_BOX_TOP ?ID ?Y))
          (IS ?RIGHT (PLUS ?X ?WIDTH))
          (IS ?BOTTOM (PLUS ?Y ?HEIGHT))
          (asserta (BOUNDING_BOX_RIGHT ?ID ?RIGHT))
          (asserta (BOUNDING_BOX_BOTTOM ?ID ?BOTTOM)))
(PAIP::<- (CREATETEXTBOUNDINGBOX ?ID)
          (GEOMETRY_CENTER_X ?ID ?CX)
          (GEOMETRY_TOP_Y ?ID ?Y)
          (GEOMETRY_W ?ID ?HALFWIDTH)
          (GEOMETRY_H ?ID ?HEIGHT)
          (IS ?X (MINUS ?CX ?HALFWIDTH))
          (asserta (BOUNDING_BOX_LEFT ?ID ?X))
          (asserta (BOUNDING_BOX_TOP ?ID ?Y))
          (IS ?RIGHT (PLUS ?CX ?HALFWIDTH))
          (IS ?BOTTOM (PLUS ?Y ?HEIGHT))
          (asserta (BOUNDING_BOX_RIGHT ?ID ?RIGHT))
          (asserta (BOUNDING_BOX_BOTTOM ?ID ?BOTTOM)))
(PAIP::<- (CREATEELLIPSEBOUNDINGBOX ?ID)
          (GEOMETRY_CENTER_X ?ID ?CX)
          (GEOMETRY_CENTER_Y ?ID ?CY)
          (GEOMETRY_W ?ID ?HALFWIDTH)
          (GEOMETRY_H ?ID ?HALFHEIGHT)
          (IS ?LEFT (MINUS ?CX ?HALFWIDTH))
          (IS ?TOP (MINUS ?CY ?HALFHEIGHT))
          (asserta (BOUNDING_BOX_LEFT ?ID ?LEFT))
          (asserta (BOUNDING_BOX_TOP ?ID ?TOP))
          (IS ?RIGHT (PLUS ?CX ?HALFWIDTH))
          (IS ?BOTTOM (PLUS ?CY ?HALFHEIGHT))
          (asserta (BOUNDING_BOX_RIGHT ?ID ?RIGHT))
          (asserta (BOUNDING_BOX_BOTTOM ?ID ?BOTTOM)))
