(in-package :arrowgram)

(paiprolog:<- (text-completely-inside-box ?TextID ?BubbleID)
    (point-completely-inside-bounding-box ?TextID ?BubbleID))

(defun find-comments ()
  (let ((all-speechbubble-pairs (paiprolog:prolog-collect (?bid ?tid)
                             (speechbubble ?bid)
                             (text ?tid ?)
                             (text-completely-inside-box ?tid ?bid))))
    (format *error-output* "~&~%speechbubbles ~S~%" all-speechbubble-pairs)
    (mapc #'(lambda (pair)
              (let ((tid (second pair)))
                (paiprolog::add-clause `((used ,tid)))
                (paiprolog::add-clause `((comment ,tid)))))
          all-speechbubble-pairs)))
