(in-package "ARROWGRAMS/ESA-TRANSPILER")
(proclaim '(optimize (debug 3) (safety 3) (speed 0)))


(defmethod rmSpaces-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "rmSpaces")
(cond
((pasm:parser-success? (pasm:lookahead? p :SPACE)))
((pasm:parser-success? (pasm:lookahead? p :COMMENT)))
( t  (pasm:accept p) 
)
)

)

(defmethod esa-dsl-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "esa-dsl")
(pasm::pasm-filter-stream p #'rmSpaces-PASS3)
(pasm:call-external p #'$esaprogram__BeginScope)
(pasm:call-external p #'$classes__FromProgram_BeginScope)
(pasm:call-rule p #'type-decls-PASS3)
(pasm:call-rule p #'situations-PASS3)
(pasm:call-rule p #'classes-PASS3)
(pasm:call-external p #'$whenDeclarations__FromProgram_BeginScope)
(pasm:call-rule p #'parse-whens-and-scripts-PASS3)
(pasm:call-external p #'$whenDeclarations__EndScope)
(pasm:input p :EOF)
(pasm:call-external p #'$classes__EndScope)
(pasm:call-external p #'$esaprogram__Output)
)

(defmethod keyword-symbol-PASS3 ((p pasm:parser)) ;; predicate
(cond
((pasm:parser-success? (pasm:lookahead? p :SYMBOL))
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "type"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "class"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "create"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "end"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "method"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "script"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "let"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "set"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "in"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "loop"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "if"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "then"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "else"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "when"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "situation"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "or"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "true"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "false"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "exit-map"))(return-from keyword-symbol-PASS3 pasm:+succeed+)
)
( t (return-from keyword-symbol-PASS3 pasm:+fail+)
)
)

)
( t (return-from keyword-symbol-PASS3 pasm:+fail+)
)
)

)

(defmethod non-keyword-symbol-PASS3 ((p pasm:parser)) ;; predicate
(cond
((pasm:parser-success? (pasm:lookahead? p :SYMBOL))
(cond
((pasm:parser-success? (pasm:call-predicate p #'keyword-symbol-PASS3))(return-from non-keyword-symbol-PASS3 pasm:+fail+)
)
( t (return-from non-keyword-symbol-PASS3 pasm:+succeed+)
)
)

)
( t (return-from non-keyword-symbol-PASS3 pasm:+fail+)
)
)

)

(defmethod type-decls-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "type-decls")
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "type"))(pasm:call-rule p #'type-decl-PASS3)
)
( t (return)
)
)

)

)

(defmethod type-decl-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "type-decl")
(pasm:input-symbol p "type")
(pasm:call-rule p #'esaSymbol-in-decl-PASS3)
)

(defmethod situations-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "situations")
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "situation"))(pasm:call-rule p #'parse-situation-def-PASS3)
)
( t (return)
)
)

)

)

(defmethod parse-situation-def-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "parse-situation-def")
(pasm:input-symbol p "situation")
(pasm:call-rule p #'esaSymbol-in-decl-PASS3)
)

(defmethod classes-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "classes")
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "class"))(pasm:call-rule p #'class-def-PASS3)
)
( t (return)
)
)

)

)

(defmethod parse-whens-and-scripts-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "parse-whens-and-scripts")
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "when"))(pasm:call-rule p #'when-declaration-PASS3)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "script"))(pasm:call-rule p #'script-implementation-PASS3)
)
( t (return)
)
)

)

)

(defmethod class-def-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "class-def")
(pasm:input-symbol p "class")
(pasm:call-rule p #'esaSymbol-in-decl-PASS3)
(pasm:call-rule p #'field-decl-PASS3)
(loop
(cond
((pasm:parser-success? (pasm:call-predicate p #'field-decl-begin-PASS3))(pasm:call-rule p #'field-decl-PASS3)
)
( t (return)
)
)

)

(pasm:input-symbol p "end")
(pasm:input-symbol p "class")
)

(defmethod field-decl-begin-PASS3 ((p pasm:parser)) ;; predicate
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(return-from field-decl-begin-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:call-predicate p #'non-keyword-symbol-PASS3))(return-from field-decl-begin-PASS3 pasm:+succeed+)
)
( t (return-from field-decl-begin-PASS3 pasm:+fail+)
)
)

)

(defmethod field-decl-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "field-decl")
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(pasm:input-symbol p "map")
(pasm:call-rule p #'esaSymbol-in-decl-PASS3)
)
((pasm:parser-success? (pasm:call-predicate p #'non-keyword-symbol-PASS3))(pasm:call-rule p #'esaSymbol-in-decl-PASS3)
)
)

)

(defmethod when-declaration-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "when-declaration")
(pasm:input-symbol p "when")
(pasm:call-rule p #'situation-ref-PASS3)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "or"))(pasm:call-rule p #'or-situation-PASS3)
)
( t (return)
)
)

)

(pasm:call-rule p #'class-ref-PASS3)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "script"))(pasm:call-rule p #'script-declaration-PASS3)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "method"))(pasm:call-rule p #'method-declaration-PASS3)
)
( t (return)
)
)

)

(pasm:input-symbol p "end")
(pasm:input-symbol p "when")
)

(defmethod situation-ref-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "situation-ref")
(pasm:call-rule p #'esaSymbol-in-decl-PASS3)
)

(defmethod or-situation-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "or-situation")
(pasm:input-symbol p "or")
(pasm:call-rule p #'situation-ref-PASS3)
)

(defmethod class-ref-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "class-ref")
(pasm:call-rule p #'esaSymbol-in-decl-PASS3)
)

(defmethod method-declaration-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "method-declaration")
(pasm:input-symbol p "method")
(pasm:call-rule p #'esaSymbol-in-decl-PASS3)
(pasm:call-rule p #'formals-PASS3)
(pasm:call-rule p #'return-type-declaration-PASS3)
)

(defmethod script-declaration-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "script-declaration")
(pasm:input-symbol p "script")
(pasm:call-rule p #'esaSymbol-in-decl-PASS3)
(pasm:call-rule p #'formals-PASS3)
(pasm:call-rule p #'return-type-declaration-PASS3)
)

(defmethod formals-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "formals")
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\())(pasm:input-char p #\()
(pasm:call-rule p #'type-list-PASS3)
(pasm:input-char p #\))
)
( t )
)

)

(defmethod type-list-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "type-list")
(pasm:call-rule p #'esaSymbol-PASS3)
(loop
(cond
((pasm:parser-success? (pasm:call-predicate p #'non-keyword-symbol-PASS3))(pasm:call-rule p #'esaSymbol-PASS3)
)
( t (return)
)
)

)

)

(defmethod return-type-declaration-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "return-type-declaration")
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\>))(pasm:input-char p #\>)
(pasm:input-char p #\>)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(pasm:input-symbol p "map")
(pasm:call-rule p #'esaSymbol-PASS3)
)
( t (pasm:call-rule p #'esaSymbol-PASS3)
)
)

)
( t )
)

)

(defmethod esaSymbol-in-decl-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "esaSymbol-in-decl")
(pasm:call-rule p #'esaSymbol-PASS3)
(pasm:call-external p #'$name__IgnoreInPass2)
)

(defmethod script-implementation-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "script-implementation")
(pasm:input-symbol p "script")
(pasm:call-rule p #'esaSymbol-PASS3)
(pasm:call-external p #'$esaclass__LookupFromClasses_BeginScope)
(pasm:call-external p #'$methodsTable__FromClass_BeginScope)
(pasm:call-rule p #'esaSymbol-PASS3)
(pasm:call-external p #'$scriptDeclaration__LookupFromTable_BeginScope)
(pasm:call-rule p #'optional-formals-definition-PASS3)
(pasm:call-rule p #'optional-return-type-definition-PASS3)
(pasm:call-rule p #'script-body-PASS3)
(pasm:call-external p #'$scriptDeclaration__SetField_implementation_from_implementation)
(pasm:input-symbol p "end")
(pasm:input-symbol p "script")
(pasm:call-external p #'$scriptDeclaration__EndScope)
(pasm:call-external p #'$methodsTable__EndScope)
(pasm:call-external p #'$esaclass__EndScope)
)

(defmethod optional-formals-definition-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "optional-formals-definition")
(pasm:call-external p #'$scriptDeclaration__ClearFormalsInBootstrap)
(pasm:call-external p #'$formalList__NewScope)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\())(pasm:input-char p #\()
(pasm:call-rule p #'untyped-formals-definition-PASS3)
(pasm:input-char p #\))
)
( t (return)
)
)

)

(pasm:call-external p #'$formalList__Output)
(pasm:call-external p #'$scriptDeclaration__SetField_formalList_from_formalList)
)

(defmethod untyped-formals-definition-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "untyped-formals-definition")
(loop
(cond
((pasm:parser-success? (pasm:call-predicate p #'non-keyword-symbol-PASS3))(pasm:call-rule p #'esaSymbol-PASS3)
(pasm:call-external p #'$formalList__AppendFrom_name)
)
( t (return)
)
)

)

)

(defmethod optional-return-type-definition-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "optional-return-type-definition")
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\>))(pasm:input-char p #\>)
(pasm:input-char p #\>)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(pasm:input-symbol p "map")
(pasm:call-rule p #'esaSymbol-in-decl-PASS3)
)
( t (pasm:call-rule p #'esaSymbol-in-decl-PASS3)
)
)

)
( t )
)

)

(defmethod script-body-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "script-body")
(pasm:call-external p #'$implementation__NewScope)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "let"))(pasm:call-rule p #'let-statement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(pasm:call-rule p #'map-statement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "set"))(pasm:call-rule p #'set-statement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "exit-map"))(pasm:call-rule p #'exit-map-statement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "create"))(pasm:call-rule p #'create-statement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "if"))(pasm:call-rule p #'if-statement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "loop"))(pasm:call-rule p #'loop-statement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "exit-when"))(pasm:call-rule p #'exit-when-statement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
((pasm:parser-success? (pasm:lookahead-char? p #\>))(pasm:call-rule p #'return-statement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
((pasm:parser-success? (pasm:lookahead-char? p #\@))(pasm:call-rule p #'callInternalStatement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
((pasm:parser-success? (pasm:call-predicate p #'non-keyword-symbol-PASS3))(pasm:call-rule p #'callExternalStatement-PASS3)
(pasm:call-external p #'$implementation__AppendFrom_statement)
)
( t (return)
)
)

)

(pasm:call-external p #'$implementation__Output)
)

(defmethod callInternalStatement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "callInternalStatement")
(pasm:input-char p #\@)
(pasm:call-rule p #'esa-expr-in-statement-PASS3)
(pasm:call-external p #'$functionReference__NewScope)
(pasm:call-external p #'$functionReference__CoerceFrom_expression)
(pasm:call-external p #'$functionReference__Output)
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$callInternalStatement__NewScope)
(pasm:call-external p #'$callInternalStatement__SetField_functionReference_from_functionReference)
(pasm:call-external p #'$callInternalStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_callInternalStatement)
(pasm:call-external p #'$statement__Output)
)

(defmethod callExternalStatement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "callExternalStatement")
(pasm:call-rule p #'esa-expr-in-statement-PASS3)
(pasm:call-external p #'$functionReference__NewScope)
(pasm:call-external p #'$functionReference__CoerceFrom_expression)
(pasm:call-external p #'$functionReference__Output)
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$callExternalStatement__NewScope)
(pasm:call-external p #'$callExternalStatement__SetField_functionReference_from_functionReference)
(pasm:call-external p #'$callExternalStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_callExternalStatement)
(pasm:call-external p #'$statement__Output)
)

(defmethod let-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "let-statement")
(pasm:input-symbol p "let")
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$letStatement__NewScope)
(pasm:call-rule p #'esaSymbol-in-statement-PASS3)
(pasm:call-external p #'$varName__NewScope)
(pasm:call-external p #'$varName__CoerceFrom_name)
(pasm:call-external p #'$varName__Output)
(pasm:call-external p #'$letStatement__SetField_varName_from_varName)
(pasm:input-char p #\=)
(pasm:call-rule p #'esa-expr-in-statement-PASS3)
(pasm:call-external p #'$letStatement__SetField_expression_from_expression)
(pasm:input-symbol p "in")
(pasm:call-rule p #'script-body-PASS3)
(pasm:call-external p #'$letStatement__SetField_implementation_from_implementation)
(pasm:input-symbol p "end")
(pasm:input-symbol p "let")
(pasm:call-external p #'$letStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_letStatement)
(pasm:call-external p #'$statement__Output)
)

(defmethod map-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "map-statement")
(pasm:input-symbol p "map")
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$mapStatement__NewScope)
(pasm:call-rule p #'esaSymbol-in-statement-PASS3)
(pasm:call-external p #'$varName__NewScope)
(pasm:call-external p #'$varName__CoerceFrom_name)
(pasm:call-external p #'$varName__Output)
(pasm:call-external p #'$mapStatement__SetField_varName_from_varName)
(pasm:input-char p #\=)
(pasm:call-rule p #'esa-expr-in-statement-PASS3)
(pasm:call-external p #'$mapStatement__SetField_expression_from_expression)
(pasm:input-symbol p "in")
(pasm:call-rule p #'script-body-PASS3)
(pasm:call-external p #'$mapStatement__SetField_implementation_from_implementation)
(pasm:input-symbol p "end")
(pasm:input-symbol p "map")
(pasm:call-external p #'$mapStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_mapStatement)
(pasm:call-external p #'$statement__Output)
)

(defmethod set-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "set-statement")
(pasm:input-symbol p "set")
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$setStatement__NewScope)
(pasm:call-rule p #'esa-expr-in-statement-PASS3)
(pasm:call-external p #'$lval__NewScope)
(pasm:call-external p #'$lval__CoerceFrom_expression)
(pasm:call-external p #'$lval__Output)
(pasm:call-external p #'$setStatement__SetField_lval_from_lval)
(pasm:input-char p #\=)
(pasm:call-rule p #'esa-expr-in-statement-PASS3)
(pasm:call-external p #'$setStatement__SetField_expression_from_expression)
(pasm:call-external p #'$setStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_setStatement)
(pasm:call-external p #'$statement__Output)
)

(defmethod exit-map-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "exit-map-statement")
(pasm:input-symbol p "exit-map")
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$exitMapStatement__NewScope)
(pasm:call-external p #'$exitMapStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_exitMapStatement)
(pasm:call-external p #'$statement__Output)
)

(defmethod loop-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "loop-statement")
(pasm:input-symbol p "loop")
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$loopStatement__NewScope)
(pasm:call-rule p #'script-body-PASS3)
(pasm:call-external p #'$loopStatement__SetField_implementation_from_implementation)
(pasm:call-external p #'$loopStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_loopStatement)
(pasm:call-external p #'$statement__Output)
(pasm:input-symbol p "end")
(pasm:input-symbol p "loop")
)

(defmethod exit-when-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "exit-when-statement")
(pasm:input-symbol p "exit-when")
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$exitWhenStatement__NewScope)
(pasm:call-rule p #'esa-expr-in-statement-PASS3)
(pasm:call-external p #'$exitWhenStatement__SetField_expression_from_expression)
(pasm:call-external p #'$exitWhenStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_exitWhenStatement)
(pasm:call-external p #'$statement__Output)
)

(defmethod script-call-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "script-call")
(pasm:input-char p #\@)
(pasm:call-rule p #'esa-expr-in-statement-PASS3)
)

(defmethod method-call-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "method-call")
(pasm:call-rule p #'esa-expr-in-statement-PASS3)
)

(defmethod esaSymbol-in-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "esaSymbol-in-statement")
(pasm:call-rule p #'esaSymbol-PASS3)
)

(defmethod esa-expr-in-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "esa-expr-in-statement")
(pasm:call-rule p #'esa-expr-PASS3)
)

(defmethod return-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "return-statement")
(pasm:input-char p #\>)
(pasm:input-char p #\>)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "true"))(pasm:input-symbol p "true")
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$returnTrueStatement__NewScope)
(pasm:call-rule p #'$fetchMethodName-PASS3)
(pasm:call-external p #'$returnTrueStatement__SetField_methodName_from_methodName)
(pasm:call-external p #'$returnTrueStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_returnTrueStatement)
(pasm:call-external p #'$statement__Output)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "false"))(pasm:input-symbol p "false")
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$returnFalseStatement__NewScope)
(pasm:call-rule p #'$fetchMethodName-PASS3)
(pasm:call-external p #'$returnFalseStatement__SetField_methodName_from_methodName)
(pasm:call-external p #'$returnFalseStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_returnFalseStatement)
(pasm:call-external p #'$statement__Output)
)
( t (pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$returnValueStatement__NewScope)
(pasm:call-rule p #'esaSymbol-in-statement-PASS3)
(pasm:call-external p #'$returnValueStatement__SetField_name_from_name)
(pasm:call-rule p #'$fetchMethodName-PASS3)
(pasm:call-external p #'$returnValueStatement__SetField_methodName_from_methodName)
(pasm:call-external p #'$returnValueStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_returnValueStatement)
(pasm:call-external p #'$statement__Output)
)
)

)

(defmethod $fetchMethodName-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "$fetchMethodName")
(pasm:call-external p #'$methodName__NewScope)
(pasm:call-external p #'$name__NewScope)
(pasm:call-external p #'$name__FromScriptDeclaration_GetField_methodName_NewScope)
(pasm:call-external p #'$name__Output)
(pasm:call-external p #'$methodName__CoerceFrom_name)
(pasm:call-external p #'$methodName__Output)
)

(defmethod create-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "create-statement")
(pasm:input-symbol p "create")
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$createStatement__NewScope)
(pasm:call-rule p #'esaSymbol-in-statement-PASS3)
(pasm:call-external p #'$varName__NewScope)
(pasm:call-external p #'$varName__CoerceFrom_name)
(pasm:call-external p #'$varName__Output)
(pasm:call-external p #'$createStatement__SetField_varName_from_varName)
(pasm:input-char p #\=)
(pasm:call-external p #'$indirectionKind__NewScope)
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\*))(pasm:input-char p #\*)
(pasm:call-external p #'$indirectionKind__SetEnum_indirect)
)
( t (pasm:call-external p #'$indirectionKind__SetEnum_direct)
)
)

(pasm:call-external p #'$indirectionKind__Output)
(pasm:call-external p #'$createStatement__SetField_indirectionKind_from_indirectionKind)
(pasm:call-rule p #'class-ref-in-statement-PASS3)
(pasm:call-external p #'$createStatement__SetField_name_from_name)
(pasm:input-symbol p "in")
(pasm:call-rule p #'script-body-PASS3)
(pasm:call-external p #'$createStatement__SetField_implementation_from_implementation)
(pasm:input-symbol p "end")
(pasm:input-symbol p "create")
(pasm:call-external p #'$createStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_createStatement)
(pasm:call-external p #'$statement__Output)
)

(defmethod class-ref-in-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "class-ref-in-statement")
(pasm:call-rule p #'esaSymbol-in-statement-PASS3)
)

(defmethod if-statement-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "if-statement")
(pasm:call-external p #'$statement__NewScope)
(pasm:call-external p #'$ifStatement__NewScope)
(pasm:input-symbol p "if")
(pasm:call-rule p #'esa-expr-in-statement-PASS3)
(pasm:call-external p #'$ifStatement__SetField_expression_from_expression)
(pasm:input-symbol p "then")
(pasm:call-rule p #'script-body-PASS3)
(pasm:call-external p #'$thenPart__NewScope)
(pasm:call-external p #'$thenPart__CoerceFrom_implementation)
(pasm:call-external p #'$thenPart__Output)
(pasm:call-external p #'$ifStatement__SetField_thenPart_from_thenPart)
(pasm:call-external p #'$elsePart__NewScope)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "else"))(pasm:input-symbol p "else")
(pasm:call-rule p #'script-body-PASS3)
(pasm:call-external p #'$elsePart__CoerceFrom_implementation)
)
( t )
)

(pasm:call-external p #'$elsePart__Output)
(pasm:call-external p #'$ifStatement__SetField_elsePart_from_elsePart)
(pasm:input-symbol p "end")
(pasm:input-symbol p "if")
(pasm:call-external p #'$ifStatement__Output)
(pasm:call-external p #'$statement__CoerceFrom_ifStatement)
(pasm:call-external p #'$statement__Output)
)

(defmethod esa-expr-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "esa-expr")
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\@))(pasm:input-char p #\@)
)
( t )
)

(pasm:call-external p #'$expression__NewScope)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "true"))(pasm:input-symbol p "true")
(pasm:call-external p #'$ekind__NewScope)
(pasm:call-external p #'$ekind__SetEnum_true)
(pasm:call-external p #'$ekind__Output)
(pasm:call-external p #'$expression__SetField_ekind_from_ekind)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "false"))(pasm:input-symbol p "false")
(pasm:call-external p #'$ekind__NewScope)
(pasm:call-external p #'$ekind__SetEnum_false)
(pasm:call-external p #'$ekind__Output)
(pasm:call-external p #'$expression__SetField_ekind_from_ekind)
)
( t (pasm:call-external p #'$ekind__NewScope)
(pasm:call-external p #'$ekind__SetEnum_object)
(pasm:call-external p #'$ekind__Output)
(pasm:call-external p #'$expression__SetField_ekind_from_ekind)
(pasm:call-rule p #'object__-PASS3)
(pasm:call-external p #'$expression__SetField_object_from_object)
)
)

(pasm:call-external p #'$expression__Output)
)

(defmethod object__-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__")
(pasm:call-external p #'$object__NewScope)
(pasm:call-rule p #'object__name-PASS3)
(pasm:call-external p #'$object__SetField_name_from_name)
(pasm:call-external p #'$fieldMap__NewScope)
(pasm:call-rule p #'object__fields-PASS3)
(pasm:call-external p #'$fieldMap__Output)
(pasm:call-external p #'$object__SetField_fieldMap_from_fieldMap)
(pasm:call-external p #'$object__Output)
)

(defmethod object__name-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__name")
(pasm:call-rule p #'esaSymbol-PASS3)
)

(defmethod object__fields-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__fields")
(loop
(cond
((pasm:parser-success? (pasm:call-predicate p #'object__field_p-PASS3))(pasm:call-external p #'$field__NewScope)
(pasm:call-rule p #'object__single_field-PASS3)
(pasm:call-external p #'$field__Output)
(pasm:call-external p #'$fieldMap__AppendFrom_field)
)
( t (return)
)
)

)

)

(defmethod object__field_p-PASS3 ((p pasm:parser)) ;; predicate
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\.))(return-from object__field_p-PASS3 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-char? p #\())(return-from object__field_p-PASS3 pasm:+succeed+)
)
( t (return-from object__field_p-PASS3 pasm:+fail+)
)
)

)

(defmethod object__single_field-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__single_field")
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\.))(pasm:call-rule p #'object__dotFieldName-PASS3)
(pasm:call-rule p #'object__parameterMap-PASS3)
)
((pasm:parser-success? (pasm:lookahead-char? p #\())(pasm:call-rule p #'object__parameterMap-PASS3)
(pasm:call-external p #'$abort)
)
( t )
)

)

(defmethod object__dotFieldName-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__dotFieldName")
(pasm:input-char p #\.)
(pasm:call-rule p #'esaSymbol-PASS3)
(pasm:call-external p #'$field__SetField_name_from_name)
)

(defmethod object__parameterMap-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__parameterMap")
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\())(pasm:call-external p #'$actualParameterList__NewScope)
(pasm:input-char p #\()
(pasm:call-rule p #'esa-expr-PASS3)
(pasm:call-external p #'$actualParameterList__AppendFrom_expression)
(pasm:call-rule p #'object__field__recursive-more-parameters-PASS3)
(pasm:input-char p #\))
(pasm:call-external p #'$actualParameterList__Output)
(pasm:call-external p #'$field__SetField_actualParameterList_from_actualParameterList)
)
( t )
)

)

(defmethod object__field__recursive-more-parameters-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__field__recursive-more-parameters")
(cond
((pasm:parser-success? (pasm:call-predicate p #'object__field__parameters__pred-parameterBegin-PASS3))(pasm:call-rule p #'esa-expr-PASS3)
(pasm:call-external p #'$actualParameterList__AppendFrom_expression)
(pasm:call-rule p #'object__field__recursive-more-parameters-PASS3)
)
( t )
)

)

(defmethod object__field__parameters__pred-parameterBegin-PASS3 ((p pasm:parser)) ;; predicate
(cond
((pasm:parser-success? (pasm:lookahead? p :SYMBOL))(return-from object__field__parameters__pred-parameterBegin-PASS3 pasm:+succeed+)
)
( t (return-from object__field__parameters__pred-parameterBegin-PASS3 pasm:+fail+)
)
)

)

(defmethod object__field__parameters__parameter-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__field__parameters__parameter")
(pasm:call-rule p #'esaSymbol-PASS3)
)

(defmethod esaSymbol-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "esaSymbol")
(pasm:call-external p #'$name__NewScope)
(pasm:input p :SYMBOL)
(pasm:call-external p #'$name__GetName)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\/))(pasm:input-char p #\/)
(pasm:call-external p #'$name__combine)
(pasm:input p :SYMBOL)
(pasm:call-external p #'$name__combine)
)
((pasm:parser-success? (pasm:lookahead-char? p #\-))(pasm:input-char p #\-)
(pasm:call-external p #'$name__combine)
(pasm:input p :SYMBOL)
(pasm:call-external p #'$name__combine)
)
((pasm:parser-success? (pasm:lookahead-char? p #\?))(pasm:input-char p #\?)
(pasm:call-external p #'$name__combine)
(return)
)
((pasm:parser-success? (pasm:lookahead-char? p #\'))(pasm:input-char p #\')
(pasm:call-external p #'$name__combine)
(return)
)
( t (return)
)
)

)

(pasm:call-external p #'$name__Output)
)

(defmethod print-tester-PASS3 ((p pasm:parser))
     (setf (pasm:current-rule p) "print-tester")
(pasm:call-rule p #'esa-dsl-PASS3)
)

