(in-package "ARROWGRAMS/ESA-TRANSPILER")
(proclaim '(optimize (debug 3) (safety 3) (speed 0)))


(defmethod rmSpaces-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "rmSpaces")
(cond
((pasm:parser-success? (pasm:lookahead? p :SPACE)))
((pasm:parser-success? (pasm:lookahead? p :COMMENT)))
( t  (pasm:accept p) 
)
)

)

(defmethod esa-dsl-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "esa-dsl")
(pasm::pasm-filter-stream p #'rmSpaces-PASS1)
(pasm:call-external p #'$esaprogram__NewScope)
(pasm:call-rule p #'type-decls-PASS1)
(pasm:call-external p #'$esaprogram__SetField_typeDecls_from_typeDecls)
(pasm:call-rule p #'situations-PASS1)
(pasm:call-external p #'$esaprogram__SetField_situations_from_situations)
(pasm:call-rule p #'classes-PASS1)
(pasm:call-external p #'$esaprogram__SetField_classes_from_classes)
(pasm:call-external p #'$whenDeclarations__NewScope)
(pasm:call-rule p #'parse-whens-and-scripts-PASS1)
(pasm:call-external p #'$whenDeclarations__Output)
(pasm:call-external p #'$esaprogram__SetField_whenDeclarations_from_whenDeclarations)
(pasm:call-external p #'$esaprogram__Output)
(pasm:input p :EOF)
)

(defmethod keyword-symbol-PASS1 ((p pasm:parser)) ;; predicate
(cond
((pasm:parser-success? (pasm:lookahead? p :SYMBOL))
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "type"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "class"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "create"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "end"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "method"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "script"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "let"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "set"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "in"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "loop"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "if"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "then"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "else"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "when"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "situation"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "or"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "true"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "false"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "exit-map"))(return-from keyword-symbol-PASS1 pasm:+succeed+)
)
( t (return-from keyword-symbol-PASS1 pasm:+fail+)
)
)

)
( t (return-from keyword-symbol-PASS1 pasm:+fail+)
)
)

)

(defmethod non-keyword-symbol-PASS1 ((p pasm:parser)) ;; predicate
(cond
((pasm:parser-success? (pasm:lookahead? p :SYMBOL))
(cond
((pasm:parser-success? (pasm:call-predicate p #'keyword-symbol-PASS1))(return-from non-keyword-symbol-PASS1 pasm:+fail+)
)
( t (return-from non-keyword-symbol-PASS1 pasm:+succeed+)
)
)

)
( t (return-from non-keyword-symbol-PASS1 pasm:+fail+)
)
)

)

(defmethod type-decls-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "type-decls")
(pasm:call-external p #'$typeDecls__NewScope)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "type"))(pasm:call-rule p #'type-decl-PASS1)
(pasm:call-external p #'$typeDecls__AppendFrom_typeDecl)
)
( t (return)
)
)

)

(pasm:call-external p #'$typeDecls__Output)
)

(defmethod type-decl-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "type-decl")
(pasm:call-external p #'$typeDecl__NewScope)
(pasm:input-symbol p "type")
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$typeDecl__SetField_name_from_name)
(pasm:call-external p #'$typeDecl__Output)
)

(defmethod situations-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "situations")
(pasm:call-external p #'$situations__NewScope)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "situation"))(pasm:call-rule p #'parse-situation-def-PASS1)
)
( t (return)
)
)

)

(pasm:call-external p #'$situations__Output)
)

(defmethod parse-situation-def-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "parse-situation-def")
(pasm:input-symbol p "situation")
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$situationDefinition__NewScope)
(pasm:call-external p #'$situationDefinition__CoerceFrom_name)
(pasm:call-external p #'$situationDefinition__Output)
(pasm:call-external p #'$situations__AppendFrom_situationDefinition)
)

(defmethod classes-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "classes")
(pasm:call-external p #'$classes__NewScope)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "class"))(pasm:call-rule p #'class-def-PASS1)
(pasm:call-external p #'$classes__AppendFrom_esaclass)
)
( t (return)
)
)

)

(pasm:call-external p #'$classes__Output)
)

(defmethod parse-whens-and-scripts-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "parse-whens-and-scripts")
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "when"))(pasm:call-rule p #'when-declaration-PASS1)
(pasm:call-external p #'$whenDeclarations__AppendFrom_whenDeclaration)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "script"))(pasm:call-rule p #'script-implementation-PASS1)
)
( t (return)
)
)

)

)

(defmethod class-def-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "class-def")
(pasm:input-symbol p "class")
(pasm:call-external p #'$esaclass__NewScope)
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$esaclass__SetField_name_from_name)
(pasm:call-external p #'$fieldMap__NewScope)
(pasm:call-rule p #'field-decl-PASS1)
(pasm:call-external p #'$fieldMap__AppendFrom_field)
(loop
(cond
((pasm:parser-success? (pasm:call-predicate p #'field-decl-begin-PASS1))(pasm:call-rule p #'field-decl-PASS1)
(pasm:call-external p #'$fieldMap__AppendFrom_field)
)
( t (return)
)
)

)

(pasm:input-symbol p "end")
(pasm:input-symbol p "class")
(pasm:call-external p #'$fieldMap__Output)
(pasm:call-external p #'$esaclass__SetField_fieldMap_from_fieldMap)
(pasm:call-external p #'$esaclass__Output)
)

(defmethod field-decl-begin-PASS1 ((p pasm:parser)) ;; predicate
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(return-from field-decl-begin-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:call-predicate p #'non-keyword-symbol-PASS1))(return-from field-decl-begin-PASS1 pasm:+succeed+)
)
( t (return-from field-decl-begin-PASS1 pasm:+fail+)
)
)

)

(defmethod field-decl-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "field-decl")
(pasm:call-external p #'$field__NewScope)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(pasm:input-symbol p "map")
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$fkind__NewScope)
(pasm:call-external p #'$fkind__SetEnum_map)
(pasm:call-external p #'$fkind__Output)
(pasm:call-external p #'$field__SetField_fkind_from_fkind)
(pasm:call-external p #'$field__SetField_name_from_name)
)
((pasm:parser-success? (pasm:call-predicate p #'non-keyword-symbol-PASS1))(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$fkind__NewScope)
(pasm:call-external p #'$fkind__SetEnum_simple)
(pasm:call-external p #'$fkind__Output)
(pasm:call-external p #'$field__SetField_fkind_from_fkind)
(pasm:call-external p #'$field__SetField_name_from_name)
)
)

(pasm:call-external p #'$field__Output)
)

(defmethod when-declaration-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "when-declaration")
(pasm:input-symbol p "when")
(pasm:call-external p #'$whenDeclaration__NewScope)
(pasm:call-external p #'$situationReferenceList__NewScope)
(pasm:call-rule p #'situation-ref-PASS1)
(pasm:call-external p #'$situationReferenceList__AppendFrom_situationReferenceName)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "or"))(pasm:call-rule p #'or-situation-PASS1)
(pasm:call-external p #'$situationReferenceList__AppendFrom_situationReferenceName)
)
( t (return)
)
)

)

(pasm:call-external p #'$situationReferenceList__Output)
(pasm:call-external p #'$whenDeclaration__SetField_situationReferenceList_from_situationReferenceList)
(pasm:call-rule p #'class-ref-PASS1)
(pasm:call-external p #'$esaKind__NewScope)
(pasm:call-external p #'$esaKind__CoerceFrom_name)
(pasm:call-external p #'$esaKind__Output)
(pasm:call-external p #'$whenDeclaration__SetField_esaKind_from_esaKind)
(pasm:call-external p #'$methodDeclarationsAndScriptDeclarations__NewScope)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "script"))(pasm:call-rule p #'script-declaration-PASS1)
(pasm:call-external p #'$declarationMethodOrScript__NewScope)
(pasm:call-external p #'$declarationMethodOrScript__CoerceFrom_scriptDeclaration)
(pasm:call-external p #'$declarationMethodOrScript__Output)
(pasm:call-external p #'$methodDeclarationsAndScriptDeclarations__AppendFrom_declarationMethodOrScript)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "method"))(pasm:call-rule p #'method-declaration-PASS1)
(pasm:call-external p #'$declarationMethodOrScript__NewScope)
(pasm:call-external p #'$declarationMethodOrScript__CoerceFrom_methodDeclaration)
(pasm:call-external p #'$declarationMethodOrScript__Output)
(pasm:call-external p #'$methodDeclarationsAndScriptDeclarations__AppendFrom_declarationMethodOrScript)
)
( t (return)
)
)

)

(pasm:call-external p #'$methodDeclarationsAndScriptDeclarations__Output)
(pasm:call-external p #'$whenDeclaration__SetField_methodDeclarationsAndScriptDeclarations_from_methodDeclarationsAndScriptDeclarations)
(pasm:input-symbol p "end")
(pasm:input-symbol p "when")
(pasm:call-external p #'$whenDeclaration__Output)
)

(defmethod situation-ref-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "situation-ref")
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$situationReferenceName__NewScope)
(pasm:call-external p #'$situationReferenceName__CoerceFrom_name)
(pasm:call-external p #'$situationReferenceName__Output)
)

(defmethod or-situation-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "or-situation")
(pasm:input-symbol p "or")
(pasm:call-rule p #'situation-ref-PASS1)
)

(defmethod class-ref-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "class-ref")
(pasm:call-rule p #'esaSymbol-PASS1)
)

(defmethod method-declaration-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "method-declaration")
(pasm:call-external p #'$methodDeclaration__NewScope)
(pasm:input-symbol p "method")
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$methodDeclaration__SetField_name_from_name)
(pasm:call-rule p #'formals-PASS1)
(pasm:call-external p #'$methodDeclaration__SetField_formalList_from_formalList)
(pasm:call-rule p #'return-type-declaration-PASS1)
(pasm:call-external p #'$methodDeclaration__SetField_returnType_from_returnType)
(pasm:call-external p #'$methodDeclaration__Output)
)

(defmethod script-declaration-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "script-declaration")
(pasm:call-external p #'$scriptDeclaration__NewScope)
(pasm:input-symbol p "script")
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$scriptDeclaration__SetField_name_from_name)
(pasm:call-rule p #'formals-PASS1)
(pasm:call-external p #'$scriptDeclaration__SetField_formalList_from_formalList)
(pasm:call-rule p #'return-type-declaration-PASS1)
(pasm:call-external p #'$scriptDeclaration__SetField_returnType_from_returnType)
(pasm:call-external p #'$scriptDeclaration__Output)
)

(defmethod formals-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "formals")
(pasm:call-external p #'$formalList__NewScope)
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\())(pasm:input-char p #\()
(pasm:call-rule p #'type-list-PASS1)
(pasm:input-char p #\))
)
( t )
)

(pasm:call-external p #'$formalList__Output)
)

(defmethod type-list-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "type-list")
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$formalList__AppendFrom_name)
(loop
(cond
((pasm:parser-success? (pasm:call-predicate p #'non-keyword-symbol-PASS1))(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$formalList__AppendFrom_name)
)
( t (return)
)
)

)

)

(defmethod return-type-declaration-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "return-type-declaration")
(pasm:call-external p #'$returnType__NewScope)
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\>))(pasm:input-char p #\>)
(pasm:input-char p #\>)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(pasm:input-symbol p "map")
(pasm:call-external p #'$returnKind__NewScope)
(pasm:call-external p #'$returnKind__SetEnum_map)
(pasm:call-external p #'$returnKind__Output)
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$returnType__SetField_name_from_name)
)
( t (pasm:call-external p #'$returnKind__NewScope)
(pasm:call-external p #'$returnKind__SetEnum_simple)
(pasm:call-external p #'$returnKind__Output)
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$returnType__SetField_name_from_name)
)
)

)
( t (pasm:call-external p #'$returnKind__NewScope)
(pasm:call-external p #'$returnKind__SetEnum_void)
(pasm:call-external p #'$returnKind__Output)
)
)

(pasm:call-external p #'$returnType__SetField_returnKind_from_returnKind)
(pasm:call-external p #'$returnType__Output)
)

(defmethod script-implementation-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "script-implementation")
(pasm:input-symbol p "script")
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$name__IgnoreInPass1)
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$name__IgnoreInPass1)
(pasm:call-rule p #'optional-formals-definition-PASS1)
(pasm:call-rule p #'optional-return-type-definition-PASS1)
(pasm:call-rule p #'script-body-PASS1)
(pasm:input-symbol p "end")
(pasm:input-symbol p "script")
)

(defmethod optional-formals-definition-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "optional-formals-definition")
(loop
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\())(pasm:input-char p #\()
(pasm:call-rule p #'untyped-formals-definition-PASS1)
(pasm:input-char p #\))
)
( t (return)
)
)

)

)

(defmethod untyped-formals-definition-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "untyped-formals-definition")
(loop
(cond
((pasm:parser-success? (pasm:call-predicate p #'non-keyword-symbol-PASS1))(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$name__IgnoreInPass1)
)
( t (return)
)
)

)

)

(defmethod optional-return-type-definition-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "optional-return-type-definition")
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\>))(pasm:input-char p #\>)
(pasm:input-char p #\>)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(pasm:input-symbol p "map")
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$name__IgnoreInPass1)
)
( t (pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$name__IgnoreInPass1)
)
)

)
( t )
)

)

(defmethod script-body-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "script-body")
(loop
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "let"))(pasm:call-rule p #'let-statement-PASS1)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "map"))(pasm:call-rule p #'map-statement-PASS1)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "exit-map"))(pasm:call-rule p #'exit-map-statement-PASS1)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "set"))(pasm:call-rule p #'set-statement-PASS1)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "create"))(pasm:call-rule p #'create-statement-PASS1)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "if"))(pasm:call-rule p #'if-statement-PASS1)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "loop"))(pasm:call-rule p #'loop-statement-PASS1)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "exit-when"))(pasm:call-rule p #'exit-when-statement-PASS1)
)
((pasm:parser-success? (pasm:lookahead-char? p #\>))(pasm:call-rule p #'return-statement-PASS1)
)
((pasm:parser-success? (pasm:lookahead-char? p #\@))(pasm:call-rule p #'callInternalStatement-PASS1)
)
((pasm:parser-success? (pasm:call-predicate p #'non-keyword-symbol-PASS1))(pasm:call-rule p #'callExternalStatement-PASS1)
)
( t (return)
)
)

)

)

(defmethod callInternalStatement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "callInternalStatement")
(pasm:call-rule p #'esa-expr-in-statement-PASS1)
(pasm:call-external p #'$expression__IgnoreInPass1)
)

(defmethod callExternalStatement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "callExternalStatement")
(pasm:call-rule p #'esa-expr-in-statement-PASS1)
(pasm:call-external p #'$expression__IgnoreInPass1)
)

(defmethod let-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "let-statement")
(pasm:input-symbol p "let")
(pasm:call-rule p #'esaSymbol-in-statement-PASS1)
(pasm:input-char p #\=)
(pasm:call-rule p #'esa-expr-in-statement-PASS1)
(pasm:input-symbol p "in")
(pasm:call-rule p #'script-body-PASS1)
(pasm:input-symbol p "end")
(pasm:input-symbol p "let")
)

(defmethod create-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "create-statement")
(pasm:input-symbol p "create")
(pasm:call-rule p #'esaSymbol-in-statement-PASS1)
(pasm:input-char p #\=)
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\*))(pasm:input-char p #\*)
(pasm:call-rule p #'class-ref-PASS1)
(pasm:call-external p #'$name__IgnoreInPass1)
)
( t (pasm:call-rule p #'class-ref-PASS1)
(pasm:call-external p #'$name__IgnoreInPass1)
)
)

(pasm:input-symbol p "in")
(pasm:call-rule p #'script-body-PASS1)
(pasm:input-symbol p "end")
(pasm:input-symbol p "create")
)

(defmethod set-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "set-statement")
(pasm:input-symbol p "set")
(pasm:call-rule p #'esa-expr-in-statement-PASS1)
(pasm:call-external p #'$expression__IgnoreInPass1)
(pasm:input-char p #\=)
(pasm:call-rule p #'esa-expr-in-statement-PASS1)
(pasm:call-external p #'$expression__IgnoreInPass1)
)

(defmethod map-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "map-statement")
(pasm:input-symbol p "map")
(pasm:call-rule p #'esaSymbol-in-statement-PASS1)
(pasm:call-external p #'$name__IgnoreInPass1)
(pasm:input-char p #\=)
(pasm:call-rule p #'esa-expr-in-statement-PASS1)
(pasm:input-symbol p "in")
(pasm:call-rule p #'script-body-PASS1)
(pasm:input-symbol p "end")
(pasm:input-symbol p "map")
)

(defmethod exit-map-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "exit-map-statement")
(pasm:input-symbol p "exit-map")
)

(defmethod loop-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "loop-statement")
(pasm:input-symbol p "loop")
(pasm:call-rule p #'script-body-PASS1)
(pasm:input-symbol p "end")
(pasm:input-symbol p "loop")
)

(defmethod exit-when-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "exit-when-statement")
(pasm:input-symbol p "exit-when")
(pasm:call-rule p #'esa-expr-in-statement-PASS1)
)

(defmethod if-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "if-statement")
(pasm:input-symbol p "if")
(pasm:call-rule p #'esa-expr-in-statement-PASS1)
(pasm:input-symbol p "then")
(pasm:call-rule p #'script-body-PASS1)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "else"))(pasm:input-symbol p "else")
(pasm:call-rule p #'script-body-PASS1)
)
( t )
)

(pasm:input-symbol p "end")
(pasm:input-symbol p "if")
)

(defmethod script-call-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "script-call")
(pasm:input-char p #\@)
(pasm:call-rule p #'esa-expr-in-statement-PASS1)
)

(defmethod method-call-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "method-call")
(pasm:call-rule p #'esa-expr-in-statement-PASS1)
)

(defmethod return-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "return-statement")
(pasm:input-char p #\>)
(pasm:input-char p #\>)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "true"))(pasm:input-symbol p "true")
)
((pasm:parser-success? (pasm:lookahead-symbol? p "false"))(pasm:input-symbol p "false")
)
( t (pasm:call-rule p #'esaSymbol-in-statement-PASS1)
)
)

)

(defmethod esaSymbol-in-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "esaSymbol-in-statement")
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$name__IgnoreInPass1)
)

(defmethod esa-expr-in-statement-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "esa-expr-in-statement")
(pasm:call-rule p #'esa-expr-PASS1)
(pasm:call-external p #'$expression__IgnoreInPass1)
)

(defmethod esa-expr-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "esa-expr")
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\@))(pasm:input-char p #\@)
)
( t )
)

(pasm:call-external p #'$expression__NewScope)
(cond
((pasm:parser-success? (pasm:lookahead-symbol? p "true"))(pasm:input-symbol p "true")
(pasm:call-external p #'$ekind__NewScope)
(pasm:call-external p #'$ekind__SetEnum_true)
(pasm:call-external p #'$ekind__Output)
(pasm:call-external p #'$expression__SetField_ekind_from_ekind)
)
((pasm:parser-success? (pasm:lookahead-symbol? p "false"))(pasm:input-symbol p "false")
(pasm:call-external p #'$ekind__NewScope)
(pasm:call-external p #'$ekind__SetEnum_false)
(pasm:call-external p #'$ekind__Output)
(pasm:call-external p #'$expression__SetField_ekind_from_ekind)
)
( t (pasm:call-external p #'$ekind__NewScope)
(pasm:call-external p #'$ekind__SetEnum_object)
(pasm:call-external p #'$ekind__Output)
(pasm:call-external p #'$expression__SetField_ekind_from_ekind)
(pasm:call-rule p #'object__-PASS1)
(pasm:call-external p #'$expression__SetField_object_from_object)
)
)

(pasm:call-external p #'$expression__Output)
)

(defmethod object__-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__")
(pasm:call-external p #'$object__NewScope)
(pasm:call-rule p #'object__name-PASS1)
(pasm:call-external p #'$object__SetField_name_from_name)
(pasm:call-external p #'$fieldMap__NewScope)
(pasm:call-rule p #'object__fields-PASS1)
(pasm:call-external p #'$fieldMap__Output)
(pasm:call-external p #'$object__SetField_fieldMap_from_fieldMap)
(pasm:call-external p #'$object__Output)
)

(defmethod object__name-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__name")
(pasm:call-rule p #'esaSymbol-PASS1)
)

(defmethod object__fields-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__fields")
(loop
(cond
((pasm:parser-success? (pasm:call-predicate p #'object__field_p-PASS1))(pasm:call-external p #'$field__NewScope)
(pasm:call-rule p #'object__single_field-PASS1)
(pasm:call-external p #'$field__Output)
(pasm:call-external p #'$fieldMap__AppendFrom_field)
)
( t (return)
)
)

)

)

(defmethod object__field_p-PASS1 ((p pasm:parser)) ;; predicate
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\.))(return-from object__field_p-PASS1 pasm:+succeed+)
)
((pasm:parser-success? (pasm:lookahead-char? p #\())(return-from object__field_p-PASS1 pasm:+succeed+)
)
( t (return-from object__field_p-PASS1 pasm:+fail+)
)
)

)

(defmethod object__single_field-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__single_field")
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\.))(pasm:call-rule p #'object__dotFieldName-PASS1)
(pasm:call-rule p #'object__parameterMap-PASS1)
)
((pasm:parser-success? (pasm:lookahead-char? p #\())(pasm:call-rule p #'object__parameterMap-PASS1)
)
( t )
)

)

(defmethod object__dotFieldName-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__dotFieldName")
(pasm:input-char p #\.)
(pasm:call-rule p #'esaSymbol-PASS1)
(pasm:call-external p #'$field__SetField_name_from_name)
)

(defmethod object__parameterMap-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__parameterMap")
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\())(pasm:call-external p #'$actualParameterList__NewScope)
(pasm:input-char p #\()
(pasm:call-rule p #'esa-expr-PASS1)
(pasm:call-external p #'$actualParameterList__AppendFrom_expression)
(pasm:call-rule p #'object__field__recursive-more-parameters-PASS1)
(pasm:input-char p #\))
(pasm:call-external p #'$actualParameterList__Output)
(pasm:call-external p #'$field__SetField_actualParameterList_from_actualParameterList)
)
( t )
)

)

(defmethod object__field__recursive-more-parameters-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__field__recursive-more-parameters")
(cond
((pasm:parser-success? (pasm:call-predicate p #'object__field__parameters__pred-parameterBegin-PASS1))(pasm:call-rule p #'esa-expr-PASS1)
(pasm:call-external p #'$actualParameterList__AppendFrom_expression)
(pasm:call-rule p #'object__field__recursive-more-parameters-PASS1)
)
( t )
)

)

(defmethod object__field__parameters__pred-parameterBegin-PASS1 ((p pasm:parser)) ;; predicate
(cond
((pasm:parser-success? (pasm:lookahead? p :SYMBOL))(return-from object__field__parameters__pred-parameterBegin-PASS1 pasm:+succeed+)
)
( t (return-from object__field__parameters__pred-parameterBegin-PASS1 pasm:+fail+)
)
)

)

(defmethod object__field__parameters__parameter-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "object__field__parameters__parameter")
(pasm:call-rule p #'esaSymbol-PASS1)
)

(defmethod esaSymbol-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "esaSymbol")
(pasm:call-external p #'$name__NewScope)
(pasm:input p :SYMBOL)
(pasm:call-external p #'$name__GetName)
(loop
(cond
((pasm:parser-success? (pasm:lookahead-char? p #\/))(pasm:input-char p #\/)
(pasm:call-external p #'$name__combine)
(pasm:input p :SYMBOL)
(pasm:call-external p #'$name__combine)
)
((pasm:parser-success? (pasm:lookahead-char? p #\-))(pasm:input-char p #\-)
(pasm:call-external p #'$name__combine)
(pasm:input p :SYMBOL)
(pasm:call-external p #'$name__combine)
)
((pasm:parser-success? (pasm:lookahead-char? p #\?))(pasm:input-char p #\?)
(pasm:call-external p #'$name__combine)
(return)
)
((pasm:parser-success? (pasm:lookahead-char? p #\'))(pasm:input-char p #\')
(pasm:call-external p #'$name__combine)
(return)
)
( t (return)
)
)

)

(pasm:call-external p #'$name__Output)
)

(defmethod tester-PASS1 ((p pasm:parser))
     (setf (pasm:current-rule p) "tester")
(pasm::pasm-filter-stream p #'rmSpaces-PASS1)
(pasm:call-rule p #'esa-expr-PASS1)
(pasm:call-external p #'$bp)
)

