(in-package "ARROWGRAMS/ESA-TRANSPILER")

(defmethod $mech-tester ((p parser))
  ;; self.fn(x)
  ($expression__NewScope p)
    ($ekind__NewScope p)
      ($ekind__SetEnum_object p)
    ($ekind__Output p)
    ($expression__SetField_ekind_From_ekind p)
    ($object__NewScope p)
      ($name__NewScope p)
  (setf (scanner:token-text (pasm:accepted-token p)) "self")
        ($name__GetName p)
      ($name__Output p)
      ($object__SetField_name_From_name p)
      ($fieldMap__NewScope p)
        ($field__NewScope p)
          ($name__NewScope p)
  (setf (scanner:token-text (pasm:accepted-token p)) "fn")
            ($name__GetName p)
          ($name__Output p)
          ($field__SetField_name_From_name p)
          ($nameMap__NewScope p)
            ($name__NewScope p)
  (setf (scanner:token-text (pasm:accepted-token p)) "x")
              ($name__GetName p)
            ($name__Output p)
            ($nameMap__AppendFrom_name p)
          ($nameMap__Output p)
          ($field__SetField_nameMap_From_nameMap p)
        ($field__Output p)
        ($fieldMap__AppendFrom_field p)
        ($field__NewScope p)
          ($name__NewScope p)
          ($name__Output p)
          ($nameMap__NewScope p)
          ($nameMap__Output p)
          ($field__SetField_nameMap_From_nameMap p)
        ($field__Output p)
        ($fieldMap__AppendFrom_field p)
      ($fieldMap__Output p)
      ($object__SetField_fieldMap_From_fieldMap p)
    ($object__Output p)
    ($expression__SetField_object_From_object p)
  ($expression__Output p)
  )

