(((:ITEM-KIND . "leaf") (:NAME . "json_array_splitter")
  (:IN-PINS "array" "json") (:OUT-PINS "items" "graph" "error")
  (:KIND . "json_array_splitter")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./json_array_splitter.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "compiler") (:IN-PINS "svg-filename")
  (:OUT-PINS "lisp" "metadata" "json" "error") (:KIND . "compiler")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./compiler.lisp"))
 ((:ITEM-KIND . "leaf") (:NAME . "part_namer") (:IN-PINS "in")
  (:OUT-PINS "out" "error") (:KIND . "part_namer")
  (:FILENAME
   . "/home/tarvydas/quicklisp/local-projects/bmfbp/build_process/parts/cl/./part_namer.lisp"))
 ((:ITEM-KIND . "graph") (:NAME . "build-compile-single-diagram")
  (:GRAPH (:NAME . "BUILD-COMPILE-SINGLE-DIAGRAM") (:INPUTS "SVG-FILENAME")
   (:OUTPUTS "GRAPH" "ERROR" "JSON-FILE-REF" "NAME")
   (:PARTS ((:PART-NAME . "COMPILER") (:KIND-NAME . "COMPILER"))
    ((:PART-NAME . "JSON_ARRAY_SPLITTER") (:KIND-NAME . "JSON_ARRAY_SPLITTER"))
    ((:PART-NAME . "PART_NAMER") (:KIND-NAME . "PART_NAMER")))
   (:WIRING
    ((:WIRE-INDEX . 0) (:SOURCES ((:PART . "PART_NAMER") (:PIN . "OUT")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "NAME"))))
    ((:WIRE-INDEX . 1) (:SOURCES ((:PART . "PART_NAMER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 2)
     (:SOURCES ((:PART . "JSON_ARRAY_SPLITTER") (:PIN . "ITEMS")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "JSON-FILE-REF"))))
    ((:WIRE-INDEX . 3)
     (:SOURCES ((:PART . "JSON_ARRAY_SPLITTER") (:PIN . "GRAPH")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "GRAPH"))))
    ((:WIRE-INDEX . 4)
     (:SOURCES ((:PART . "JSON_ARRAY_SPLITTER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 5) (:SOURCES ((:PART . "COMPILER") (:PIN . "METADATA")))
     (:RECEIVERS ((:PART . "JSON_ARRAY_SPLITTER") (:PIN . "ARRAY"))))
    ((:WIRE-INDEX . 6) (:SOURCES ((:PART . "COMPILER") (:PIN . "JSON")))
     (:RECEIVERS ((:PART . "JSON_ARRAY_SPLITTER") (:PIN . "JSON"))))
    ((:WIRE-INDEX . 7) (:SOURCES ((:PART . "COMPILER") (:PIN . "ERROR")))
     (:RECEIVERS ((:PART . "SELF") (:PIN . "ERROR"))))
    ((:WIRE-INDEX . 8) (:SOURCES ((:PART . "SELF") (:PIN . "SVG-FILENAME")))
     (:RECEIVERS ((:PART . "COMPILER") (:PIN . "SVG-FILENAME"))
      ((:PART . "PART_NAMER") (:PIN . "IN"))))))))