(in-package :arrowgrams/compiler/xform)

(PROGN
 (ESRAP:DEFRULE IR-GRAMMAR
     (AND LPAR SELF-PART RPAR))
 (ESRAP:DEFRULE SELF-PART
     (AND SELF-KINDNAME INPUTS-LIST OUTPUTS-LIST SELF-PART-LIST
          SELF-WIRING-LIST))
 (ESRAP:DEFRULE SELF-KINDNAME
     IDENT)
 (ESRAP:DEFRULE SELF-PART-LIST
     (AND LPAR PARTS RPAR))
 (ESRAP:DEFRULE SELF-WIRING-LIST
     (AND LPAR WIRES RPAR))
 (ESRAP:DEFRULE INPUTS-LIST
     (AND LPAR PIN-DECLS RPAR))
 (ESRAP:DEFRULE OUTPUTS-LIST
     (AND LPAR PIN-DECLS RPAR))
 (ESRAP:DEFRULE PARTS
     (OR PART (AND PARTS PART)))
 (ESRAP:DEFRULE PART
     (OR IDENT SELF))
 (ESRAP:DEFRULE WIRES
     (OR WIRE (AND WIRES WIRE)))
 (ESRAP:DEFRULE WIRE
     (AND LPAR PART PIN RPAR))
 (ESRAP:DEFRULE PIN-DECLS
     (OR PIN-DECL (AND PIN-DECLS PIN-DECL)))
 (ESRAP:DEFRULE PIN-DECL
     IDENT)
 (ESRAP:DEFRULE PIN
     IDENT
   (:TEXT T))
 (ESRAP:DEFRULE IDENT
     (AND STRING (* WS))
   (:FUNCTION FIRST)
   (:text t))
 (ESRAP:DEFRULE STRING
     (AND "\"" (+ NOTDQUOTE) "\""))
 (ESRAP:DEFRULE NOTDQUOTE
     (AND (ESRAP:! "\"") CHARACTER))
 (ESRAP:DEFRULE SELF
     (AND "SELF" (* WS)))
 (ESRAP:DEFRULE LPAR
     (AND "(" (* WS)))
 (ESRAP:DEFRULE RPAR
     (AND ")" (* WS)))
 (ESRAP:DEFRULE WS
     (OR " " COMMENTTOEOL EOL EOF))
 (ESRAP:DEFRULE COMMENTTOEOL
     (AND ";" (+ CHARACTER) EOF))
 (ESRAP:DEFRULE EOL
     "
")
 (ESRAP:DEFRULE EOF
     (ESRAP:! CHARACTER)))
